-- Together Forever: document vault, welfare, campaign reconciliation, data transfer, membership cards
create table if not exists app.documents (id uuid primary key default gen_random_uuid(), title text not null, document_type text not null default 'general', description text, audience_policy_id uuid references app.audience_policies(id), owner_person_id uuid references app.persons(id), current_version integer not null default 1, status text not null default 'active' check(status in ('draft','active','archived')), created_by_person_id uuid references app.persons(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists app.document_versions (id uuid primary key default gen_random_uuid(), document_id uuid not null references app.documents(id) on delete restrict, version_number integer not null, file_url text, external_provider text, external_url text, mime_type text, checksum_sha256 text, notes text, created_by_person_id uuid references app.persons(id), created_at timestamptz not null default now(), unique(document_id,version_number));
create table if not exists app.welfare_cases (id uuid primary key default gen_random_uuid(), case_number text not null unique, beneficiary_person_id uuid references app.persons(id), requested_by_person_id uuid references app.persons(id), assigned_to_person_id uuid references app.persons(id), category text not null, urgency text not null default 'normal' check(urgency in ('low','normal','high','critical')), requested_amount numeric(14,2), approved_amount numeric(14,2), currency varchar(8) not null default 'PKR', status text not null default 'submitted' check(status in ('submitted','under_review','evidence_requested','approved','partially_approved','rejected','disbursing','follow_up','closed','reopened','cancelled')), confidentiality text not null default 'restricted' check(confidentiality in ('restricted','committee','board')), summary text, decision_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), closed_at timestamptz);
create table if not exists app.welfare_case_events (id uuid primary key default gen_random_uuid(), case_id uuid not null references app.welfare_cases(id) on delete restrict, event_type text not null, amount numeric(14,2), currency varchar(8), evidence_url text, notes text, actor_person_id uuid references app.persons(id), created_at timestamptz not null default now());
create table if not exists app.campaign_contributions (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references app.campaigns(id) on delete restrict, contributor_person_id uuid references app.persons(id), amount numeric(14,2) not null check(amount>0), currency varchar(8) not null, contribution_method text not null default 'external', reference_text text, evidence_url text, anonymous boolean not null default false, sender_marked_paid_at timestamptz, received_confirmed_at timestamptz, confirmed_by_person_id uuid references app.persons(id), status text not null default 'pledged' check(status in ('pledged','payment_arranged','sender_marked_paid','received','completed','refunded','cancelled','disputed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists app.campaign_distributions (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references app.campaigns(id) on delete restrict, beneficiary_person_id uuid references app.persons(id), amount numeric(14,2) not null check(amount>0), currency varchar(8) not null, distribution_method text, reference_text text, evidence_url text, notes text, approved_by_person_id uuid references app.persons(id), confirmed_at timestamptz, created_at timestamptz not null default now());
create table if not exists app.data_transfer_jobs (id uuid primary key default gen_random_uuid(), job_type text not null check(job_type in ('import','export')), entity_type text not null, status text not null default 'draft' check(status in ('draft','uploaded','mapping','validated','ready','running','completed','completed_with_errors','failed','cancelled')), source_filename text, source_url text, mapping jsonb not null default '{}'::jsonb, validation_summary jsonb not null default '{}'::jsonb, result_url text, requested_by_person_id uuid references app.persons(id), approved_by_person_id uuid references app.persons(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists app.data_transfer_errors (id uuid primary key default gen_random_uuid(), job_id uuid not null references app.data_transfer_jobs(id) on delete restrict, row_number integer, field_name text, error_code text, message text not null, raw_value text, created_at timestamptz not null default now());
create table if not exists app.membership_card_tokens (id uuid primary key default gen_random_uuid(), person_id uuid not null references app.persons(id) on delete restrict, token_hash text not null unique, issued_at timestamptz not null default now(), expires_at timestamptz, revoked_at timestamptz, created_by_person_id uuid references app.persons(id));
