import {createHash} from 'crypto';
import {NextResponse} from 'next/server';
import {auth} from '../../../../lib/auth/server';
import {accessForAuthUser} from '../../../../lib/access';
import {db} from '../../../../lib/db';
type U={id:string};type S={user?:U|null;data?:{user?:U|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as S;const u=raw.user??raw.data?.user??null;if(!u?.id)return {e:NextResponse.json({error:'Unauthorized'},{status:401})};const a=await accessForAuthUser(u.id);if(!a||a.accountStatus!=='active')return {e:NextResponse.json({error:'Forbidden'},{status:403})};return {a};}
export async function GET(){const g=await gate();if(g.e)return g.e;const s=db();const rows=await s`select id::text,endpoint,status,created_at,updated_at from app.push_subscriptions where person_id=${g.a!.personId}::uuid and status='active' order by created_at desc`;return NextResponse.json({subscriptions:rows,configured:Boolean(process.env.NEXT_PUBLIC_WEB_PUSH_VAPID_PUBLIC_KEY)});}
export async function POST(req:Request){const g=await gate();if(g.e)return g.e;const b=await req.json() as {endpoint?:string;keys?:{p256dh?:string;auth?:string}};const endpoint=String(b.endpoint||'').trim(),p256dh=String(b.keys?.p256dh||'').trim(),authKey=String(b.keys?.auth||'').trim();if(!endpoint||!p256dh||!authKey)return NextResponse.json({error:'Complete push subscription required.'},{status:400});if(!endpoint.startsWith('https://'))return NextResponse.json({error:'Push endpoint must be HTTPS.'},{status:400});const uaHash=createHash('sha256').update(req.headers.get('user-agent')||'unknown').digest('hex');const s=db();await s`insert into app.push_subscriptions(person_id,endpoint,p256dh,auth_key,user_agent_hash,status,revoked_at,updated_at) values(${g.a!.personId}::uuid,${endpoint},${p256dh},${authKey},${uaHash},'active',null,now()) on conflict(endpoint) do update set person_id=excluded.person_id,p256dh=excluded.p256dh,auth_key=excluded.auth_key,user_agent_hash=excluded.user_agent_hash,status='active',revoked_at=null,updated_at=now()`;return NextResponse.json({ok:true},{status:201});}
export async function DELETE(req:Request){const g=await gate();if(g.e)return g.e;const b=await req.json().catch(()=>({})) as {endpoint?:string};const endpoint=String(b.endpoint||'').trim();if(!endpoint)return NextResponse.json({error:'Endpoint required.'},{status:400});const s=db();await s`update app.push_subscriptions set status='revoked',revoked_at=now(),updated_at=now() where person_id=${g.a!.personId}::uuid and endpoint=${endpoint}`;return NextResponse.json({ok:true});}
