'use client';

import { useEffect,useState } from 'react';
import Link from 'next/link';

const labels:Record<string,{title:string;subtitle:string;types:string[]}>={
  events:{title:'Events',subtitle:'Reunions, talks, get-togethers and member suggestions.',types:['get_together','talk','reunion','webinar','family_event']},
  opportunities:{title:'Jobs & Business Opportunities',subtitle:'Jobs, internships, projects and business opportunities.',types:['job','internship','business','project','volunteer']},
  marketplace:{title:'Marketplace',subtitle:'General listings, land, vehicles, gold, digital assets and software.',types:['general','land','property','vehicle','gold','digital_asset','software']},
  fundraising:{title:'Fundraising & Causes',subtitle:'Suggest causes and support approved campaigns.',types:['cause','welfare','education','memorial','emergency']},
  gallery:{title:'Gallery & Shared Media',subtitle:'Albums plus Google Drive, OneDrive and SharePoint links.',types:['gallery','event','heritage','documents']},
  businesses:{title:'Member Businesses',subtitle:'Discover and publish member/family businesses.',types:['general','professional_services','technology','healthcare','construction','education']},
  community:{title:'Community',subtitle:'Updates, needs, offers and Ask the Network posts.',types:['update','need','offer','question','announcement']},
  proposals:{title:'Governance Proposals',subtitle:'Submit proposals for board review, discussion and voting.',types:['proposal']},
};

type Row={id:string;title:string;status:string;created_at:string};
type Payload={rows:Row[];canCreate:boolean;canModerate:boolean};

export default function ModuleClient({module}:{module:string}){
 const meta=labels[module]||{title:module,subtitle:'Together Forever Network module.',types:['general']};
 const [data,setData]=useState<Payload>({rows:[],canCreate:false,canModerate:false});
 const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [type,setType]=useState(meta.types[0]);const [location,setLocation]=useState('');const [amount,setAmount]=useState('');const [currency,setCurrency]=useState('PKR');const [externalUrl,setExternalUrl]=useState('');const [audience,setAudience]=useState('network');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch(`/api/network/${module}`,{cache:'no-store'});if(r.ok)setData(await r.json());}
 useEffect(()=>{void load();},[module]);
 async function create(){setBusy(true);setMessage('');const r=await fetch(`/api/network/${module}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,description,type,eventType:type,location,amount:amount||undefined,currency,externalUrl,provider:externalUrl.includes('drive.google')?'google_drive':externalUrl.includes('1drv.ms')||externalUrl.includes('sharepoint')?'onedrive':'external',audience})});const b=await r.json();if(r.ok){setTitle('');setDescription('');setLocation('');setAmount('');setExternalUrl('');setMessage('Created successfully.');await load();}else setMessage(b.error||'Unable to create.');setBusy(false);}
 async function archive(id:string){const r=await fetch(`/api/network/${module}?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(r.ok)await load();else{const b=await r.json();setMessage(b.error||'Unable to archive.');}}
 return <main className="min-h-screen bg-[#06150d] text-white"><header className="sticky top-0 z-40 border-b border-white/10 bg-[#06150d]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><Link href="/network" className="font-bold">← Together Forever Network</Link><span className="text-xs text-white/45">{meta.title}</span></div></header><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><section className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-white/[0.07] to-transparent p-6 sm:p-8"><h1 className="text-3xl font-semibold sm:text-4xl">{meta.title}</h1><p className="mt-2 max-w-2xl text-white/55">{meta.subtitle}</p></section>
 {data.canCreate&&<section className="mt-6 rounded-3xl border border-amber-300/15 bg-amber-300/[0.04] p-5 sm:p-6"><h2 className="text-xl font-semibold">Create / Suggest</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3"/><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-white/10 bg-[#071a11] px-4 py-3">{meta.types.map(t=><option key={t}>{t}</option>)}</select><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" rows={4} className="md:col-span-2 rounded-xl border border-white/10 bg-black/20 px-4 py-3"/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Location / area" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3"/><input value={externalUrl} onChange={e=>setExternalUrl(e.target.value)} placeholder="Google Drive / OneDrive / external link" className="rounded-xl border border-white/10 bg-black/20 px-4 py-3"/><div className="flex gap-2"><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} placeholder="Amount / price" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-4 py-3"/><select value={currency} onChange={e=>setCurrency(e.target.value)} className="rounded-xl border border-white/10 bg-[#071a11] px-3"><option>PKR</option><option>USD</option><option>GBP</option><option>AED</option></select></div><select value={audience} onChange={e=>setAudience(e.target.value)} className="rounded-xl border border-white/10 bg-[#071a11] px-4 py-3"><option value="network">Entire Network</option><option value="m_only">Alumni Members Only</option><option value="family">Entire Family Network</option></select></div>{message&&<p className="mt-4 rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white/70">{message}</p>}<button onClick={()=>void create()} disabled={busy||!title.trim()} className="mt-4 rounded-xl bg-amber-300 px-5 py-3 font-semibold text-[#07120b] disabled:opacity-40">{busy?'Saving…':'Submit'}</button></section>}
 <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-semibold">Live records</h2><span className="text-xs text-white/40">{data.rows.length} records</span></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.rows.map(r=><article key={r.id} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold">{r.title}</h3><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] uppercase text-white/50">{r.status}</span></div><p className="mt-3 text-xs text-white/35">{new Date(r.created_at).toLocaleString()}</p><div className="mt-4 flex gap-2"><button onClick={()=>void archive(r.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/55 hover:bg-white/5">Archive / remove</button></div></article>)}{!data.rows.length&&<div className="rounded-2xl border border-dashed border-white/10 p-8 text-sm text-white/40">No records yet. The first approved network activity will appear here from Neon.</div>}</div></section></div></main>;
}
