import Link from 'next/link';
import { redirect } from 'next/navigation';
import { Coins, ShieldCheck } from 'lucide-react';
import { auth } from '../../../lib/auth/server';
import { accessForAuthUser,hasPermission } from '../../../lib/access';
import { db } from '../../../lib/db';
import ForeverPointsCaseForm from './support-form';
import ReviewCases from './review-cases';

export const dynamic='force-dynamic';
type SessionUser={id:string};type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
export default async function ForeverPointsPage(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)redirect('/auth/sign-in');const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')redirect('/network');const sql=db();const account=await sql`select a.id::text,coalesce(sum(l.points_delta),0)::bigint as balance from app.foreverpoints_accounts a left join app.foreverpoints_ledger l on l.account_id=a.id where a.person_id=${access.personId}::uuid group by a.id limit 1` as unknown as Array<{id:string;balance:string}>;const cases=await sql`select id::text,case_number,case_type,status,subject,opened_at from app.foreverpoints_cases where person_id=${access.personId}::uuid order by opened_at desc limit 50` as unknown as Array<{id:string;case_number:string;case_type:string;status:string;subject:string;opened_at:string}>;const canReview=hasPermission(access,'foreverpoints.case.review')||hasPermission(access,'foreverpoints.case.resolve');return <main className="min-h-screen bg-[#06150d] text-white"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><Link href="/network" className="text-sm text-white/55">← Network</Link><section className="mt-5 rounded-[2rem] border border-amber-300/20 bg-amber-300/[0.05] p-7 sm:p-9"><div className="flex items-center gap-3"><Coins className="h-9 w-9 text-amber-300"/><div><h1 className="text-3xl font-semibold">ForeverPoints</h1><p className="text-sm text-white/50">Tamper-evident credits ledger</p></div></div><div className="mt-8 text-5xl font-semibold">{account[0]?.balance||'0'} <span className="text-lg text-amber-200">FP</span></div><div className="mt-5 flex items-center gap-2 text-xs text-emerald-200"><ShieldCheck className="h-4 w-4"/> Append-only ledger · hash-chain integrity · disputes resolved with compensating entries</div></section><div className="mt-6 grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><ForeverPointsCaseForm/><section className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><h2 className="text-xl font-semibold">Support & correction cases</h2><div className="mt-4 space-y-3">{cases.map(c=><article key={c.id} className="rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex justify-between gap-3"><div><div className="font-semibold">{c.subject}</div><div className="mt-1 text-xs text-white/40">{c.case_number} · {c.case_type}</div></div><span className="h-fit rounded-full border border-white/10 px-2 py-1 text-[10px] uppercase text-white/50">{c.status}</span></div></article>)}{!cases.length&&<p className="text-sm text-white/40">No ForeverPoints support cases.</p>}</div></section></div>{canReview&&<ReviewCases/>}</div></main>}
