import { NextResponse } from 'next/server';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser } from '../../../../lib/access';
import { db } from '../../../../lib/db';
type SessionUser={id:string};type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
export async function GET(request:Request){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return NextResponse.json({error:'Unauthorized'},{status:401});const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')return NextResponse.json({error:'Forbidden'},{status:403});const q=(new URL(request.url).searchParams.get('q')||'').trim();if(q.length<2)return NextResponse.json({results:[]});const like='%'+q+'%';const s=db();const people=await s`select p.id::text,'person' kind,coalesce(p.display_name,p.full_name) title,mc.code subtitle,'/network/directory' href from app.persons p left join app.membership_codes mc on mc.person_id=p.id where p.account_status in ('active','deceased') and (p.id=${access.personId}::uuid or p.profile_visibility in ('network','public') or (p.profile_visibility='m_only' and ${access.relationshipPrefix}='M')) and (p.full_name ilike ${like} or coalesce(mc.code,'') ilike ${like} or coalesce(p.arm_or_service,'') ilike ${like}) limit 20`;
 const events=await s`select e.id::text,'event' kind,e.title,coalesce(e.location_name,e.event_type) subtitle,'/network/events' href from app.events e left join app.audience_policies ap on ap.id=e.audience_policy_id where e.status<>'archived' and (ap.id is null or ap.policy_type in ('public','network','family') or (ap.policy_type='m_only' and ${access.relationshipPrefix}='M') or e.suggested_by_person_id=${access.personId}::uuid) and (e.title ilike ${like} or coalesce(e.description,'') ilike ${like}) limit 20`;
 const opportunities=await s`select o.id::text,'opportunity' kind,o.title,coalesce(o.organization_name,o.opportunity_type) subtitle,'/network/opportunities' href from app.opportunities o left join app.audience_policies ap on ap.id=o.audience_policy_id where o.status<>'archived' and (ap.id is null or ap.policy_type in ('public','network','family') or (ap.policy_type='m_only' and ${access.relationshipPrefix}='M') or o.posted_by_person_id=${access.personId}::uuid) and (o.title ilike ${like} or coalesce(o.organization_name,'') ilike ${like} or coalesce(o.description,'') ilike ${like}) limit 20`;
 const listings=await s`select l.id::text,'listing' kind,l.title,concat_ws(' · ',l.listing_type,l.location_text) subtitle,'/network/marketplace' href from app.listings l left join app.audience_policies ap on ap.id=l.audience_policy_id where l.status<>'archived' and (ap.id is null or ap.policy_type in ('public','network','family') or (ap.policy_type='m_only' and ${access.relationshipPrefix}='M') or l.seller_person_id=${access.personId}::uuid) and (l.title ilike ${like} or coalesce(l.description,'') ilike ${like} or coalesce(l.location_text,'') ilike ${like}) limit 20`;
 const posts=await s`select p.id::text,'community' kind,p.title,p.post_type subtitle,'/network/community' href from app.posts p left join app.audience_policies ap on ap.id=p.audience_policy_id where p.status<>'archived' and (ap.id is null or ap.policy_type in ('public','network','family') or (ap.policy_type='m_only' and ${access.relationshipPrefix}='M') or p.author_person_id=${access.personId}::uuid) and (p.title ilike ${like} or coalesce(p.body,'') ilike ${like}) limit 20`;
 return NextResponse.json({results:[...people,...events,...opportunities,...listings,...posts].slice(0,60)});}
