import { NextResponse } from 'next/server';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser,hasPermission } from '../../../../lib/access';
import { db } from '../../../../lib/db';
import { requireStepUp } from '../../../../lib/security/step-up';

type SessionUser={id:string};type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
type RequestRow={id:string;subject_person_id:string|null;family_group_id:string|null;date_of_birth:string|null;status:string};
async function gate(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const access=await accessForAuthUser(user.id);if(!hasPermission(access,'matrimonial.review'))return {error:NextResponse.json({error:'Forbidden'},{status:403})};return {access};}
async function step(personId:string){const x=await requireStepUp(personId,'matrimonial.review');return x?NextResponse.json(x,{status:428}):null;}
export async function GET(){const g=await gate();if(g.error)return g.error;const s=db();const requests=await s`select fr.id::text,fr.title,fr.description,fr.request_data->>'lookingFor' looking_for,fr.request_data->>'locationPreference' location_preference,fr.status,fr.created_at,extract(year from age(current_date,p.date_of_birth))::int age,mc.code subject_code,rt.label relationship_label from app.family_requests fr join app.persons p on p.id=fr.subject_person_id left join app.membership_codes mc on mc.person_id=p.id left join app.relationship_types rt on rt.id=p.relationship_type_id where fr.request_type='matrimonial' and fr.status in ('pending','approved','published') order by case fr.status when 'pending' then 0 else 1 end,fr.created_at desc` as unknown as Array<Record<string,unknown>>;const matches=await s`select m.id::text,m.status,m.created_at,a.id::text request_a_id,b.id::text request_b_id,ma.code request_a_code,mb.code request_b_code,coalesce(ca.consent_status,'pending') consent_a,coalesce(cb.consent_status,'pending') consent_b,m.introduced_at from app.matrimonial_matches m join app.family_requests a on a.id=m.request_a_id join app.family_requests b on b.id=m.request_b_id left join app.membership_codes ma on ma.person_id=a.subject_person_id left join app.membership_codes mb on mb.person_id=b.subject_person_id left join app.matrimonial_match_consents ca on ca.match_id=m.id and ca.person_id=a.subject_person_id left join app.matrimonial_match_consents cb on cb.match_id=m.id and cb.person_id=b.subject_person_id order by m.created_at desc` as unknown as Array<Record<string,unknown>>;return NextResponse.json({requests,matches,privacy:'Reviewer payload intentionally excludes email and phone.'});}
export async function POST(request:Request){const g=await gate();if(g.error)return g.error;const st=await step(g.access!.personId);if(st)return st;const b=await request.json() as {action?:string;requestId?:string;requestAId?:string;requestBId?:string;matchId?:string;note?:string};const s=db();if(b.action==='request.approve'||b.action==='request.reject'){if(!b.requestId)return NextResponse.json({error:'requestId required'},{status:400});const next=b.action==='request.approve'?'published':'rejected';const rows=await s`update app.family_requests set status=${next},updated_at=now() where id=${b.requestId}::uuid and request_type='matrimonial' and status in ('pending','approved','published') returning id::text` as unknown as Array<{id:string}>;if(!rows[0])return NextResponse.json({error:'Request not found or no longer reviewable.'},{status:404});await s`insert into app.audit_logs(actor_person_id,action,object_type,object_id,after_data) values (${g.access!.personId}::uuid,${'matrimonial.'+next},'family_request',${b.requestId}::uuid,${JSON.stringify({status:next,note:b.note?.trim()||null})}::jsonb)`;return NextResponse.json({ok:true,status:next});}
if(b.action==='match.propose'){if(!b.requestAId||!b.requestBId||b.requestAId===b.requestBId)return NextResponse.json({error:'Two distinct request IDs are required.'},{status:400});const ids=[b.requestAId,b.requestBId].sort();const reqs=await s`select fr.id::text,fr.subject_person_id::text, p.family_group_id::text, p.date_of_birth,fr.status from app.family_requests fr join app.persons p on p.id=fr.subject_person_id where fr.id in (${ids[0]}::uuid,${ids[1]}::uuid) and fr.request_type='matrimonial'` as unknown as RequestRow[];if(reqs.length!==2||reqs.some(r=>r.status!=='published'))return NextResponse.json({error:'Both profiles must be published before pairing.'},{status:400});if(reqs.some(r=>!r.date_of_birth||new Date(r.date_of_birth)>new Date(new Date().setFullYear(new Date().getFullYear()-18))))return NextResponse.json({error:'Both subjects must be adults.'},{status:400});if(reqs[0].subject_person_id===reqs[1].subject_person_id)return NextResponse.json({error:'A profile cannot be matched with itself.'},{status:400});if(reqs[0].family_group_id&&reqs[0].family_group_id===reqs[1].family_group_id)return NextResponse.json({error:'Profiles in the same family group cannot be paired.'},{status:400});try{const made=await s`insert into app.matrimonial_matches(request_a_id,request_b_id,initiated_by_person_id,status) values (${ids[0]}::uuid,${ids[1]}::uuid,${g.access!.personId}::uuid,'awaiting_consent') returning id::text` as unknown as Array<{id:string}>;const matchId=made[0].id;for(const r of reqs)await s`insert into app.matrimonial_match_consents(match_id,person_id,consent_status) values (${matchId}::uuid,${r.subject_person_id}::uuid,'pending') on conflict do nothing`;await s`insert into app.matrimonial_match_events(match_id,actor_person_id,event_type,event_data) values (${matchId}::uuid,${g.access!.personId}::uuid,'match.proposed',${JSON.stringify({requestAId:ids[0],requestBId:ids[1]})}::jsonb)`;await s`insert into app.audit_logs(actor_person_id,action,object_type,object_id,after_data) values (${g.access!.personId}::uuid,'matrimonial.match.propose','matrimonial_match',${matchId}::uuid,${JSON.stringify({requestAId:ids[0],requestBId:ids[1]})}::jsonb)`;return NextResponse.json({ok:true,id:matchId},{status:201});}catch(e){const message=e instanceof Error?e.message:'Unable to propose match';return NextResponse.json({error:message.includes('unique')?'These profiles already have an active match record.':message},{status:400});}}
if(b.action==='match.introduce'){if(!b.matchId)return NextResponse.json({error:'matchId required'},{status:400});const rows=await s`update app.matrimonial_matches set status='introduced',introduced_at=now(),updated_at=now() where id=${b.matchId}::uuid and status='mutual_consent' returning id::text` as unknown as Array<{id:string}>;if(!rows[0])return NextResponse.json({error:'Mutual consent is required before introduction.'},{status:400});await s`insert into app.matrimonial_match_events(match_id,actor_person_id,event_type,event_data) values (${b.matchId}::uuid,${g.access!.personId}::uuid,'introduced',${JSON.stringify({contactReleased:false,note:b.note?.trim()||null})}::jsonb)`;return NextResponse.json({ok:true,status:'introduced'});}
return NextResponse.json({error:'Unknown action'},{status:400});}
