import { NextResponse } from 'next/server';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser,hasPermission } from '../../../../lib/access';
import { db } from '../../../../lib/db';

type SessionUser={id:string}; type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')return {error:NextResponse.json({error:'Forbidden'},{status:403})};return {access};}

export async function GET(){const g=await gate();if(g.error)return g.error;const s=db();const myReports=await s`select id::text,target_type,reason_code,details,status,resolution,created_at,updated_at from app.moderation_reports where reporter_person_id=${g.access!.personId}::uuid order by created_at desc limit 100`;const blocks=await s`select ub.blocked_person_id::text,p.full_name,mc.code,ub.reason,ub.created_at from app.user_blocks ub join app.persons p on p.id=ub.blocked_person_id left join app.membership_codes mc on mc.person_id=p.id where ub.blocker_person_id=${g.access!.personId}::uuid order by ub.created_at desc`;let queue:unknown[]=[];if(hasPermission(g.access!,'trust.moderate'))queue=await s`select mr.id::text,mr.target_type,mr.target_id::text,mr.reason_code,mr.details,mr.status,mr.created_at,rp.full_name reporter_name,rmc.code reporter_code,tp.full_name target_person_name,tmc.code target_person_code from app.moderation_reports mr join app.persons rp on rp.id=mr.reporter_person_id left join app.membership_codes rmc on rmc.person_id=rp.id left join app.persons tp on tp.id=mr.target_person_id left join app.membership_codes tmc on tmc.person_id=tp.id where mr.status not in ('closed','dismissed') order by case mr.status when 'escalated' then 0 when 'open' then 1 else 2 end,mr.created_at`;return NextResponse.json({myReports,blocks,queue,canModerate:hasPermission(g.access!,'trust.moderate')});}

export async function POST(request:Request){const g=await gate();if(g.error)return g.error;const b=await request.json() as Record<string,unknown>;const action=String(b.action||'');const s=db();try{
if(action==='report'){if(!hasPermission(g.access!,'trust.report'))return NextResponse.json({error:'Forbidden'},{status:403});const targetType=String(b.targetType||'').trim();const reason=String(b.reason||'other').trim();if(!targetType)return NextResponse.json({error:'Target type required'},{status:400});const targetId=String(b.targetId||'').trim()||null;const targetPersonCode=String(b.targetPersonCode||'').trim();let targetPersonId:string|null=null;if(targetPersonCode){const rows=await s`select person_id::text from app.membership_codes where upper(code)=upper(${targetPersonCode}) limit 1` as unknown as Array<{person_id:string}>;if(!rows[0])return NextResponse.json({error:'Target person not found'},{status:404});targetPersonId=rows[0].person_id;}const r=await s`insert into app.moderation_reports(reporter_person_id,target_type,target_id,target_person_id,reason_code,details) values (${g.access!.personId}::uuid,${targetType},${targetId}::uuid,${targetPersonId}::uuid,${reason},${String(b.details||'').trim()||null}) returning id::text` as unknown as Array<{id:string}>;return NextResponse.json({ok:true,id:r[0].id},{status:201});}
if(action==='block'){if(!hasPermission(g.access!,'trust.block'))return NextResponse.json({error:'Forbidden'},{status:403});const code=String(b.membershipCode||'').trim();const rows=await s`select person_id::text from app.membership_codes where upper(code)=upper(${code}) limit 1` as unknown as Array<{person_id:string}>;if(!rows[0])return NextResponse.json({error:'Member not found'},{status:404});if(rows[0].person_id===g.access!.personId)return NextResponse.json({error:'You cannot block yourself'},{status:400});await s`insert into app.user_blocks(blocker_person_id,blocked_person_id,reason) values (${g.access!.personId}::uuid,${rows[0].person_id}::uuid,${String(b.reason||'').trim()||null}) on conflict(blocker_person_id,blocked_person_id) do update set reason=excluded.reason`;return NextResponse.json({ok:true});}
if(action==='unblock'){if(!hasPermission(g.access!,'trust.block'))return NextResponse.json({error:'Forbidden'},{status:403});await s`delete from app.user_blocks where blocker_person_id=${g.access!.personId}::uuid and blocked_person_id=${String(b.personId||'')}::uuid`;return NextResponse.json({ok:true});}
if(action==='resolve'){if(!hasPermission(g.access!,'trust.moderate'))return NextResponse.json({error:'Forbidden'},{status:403});const reportId=String(b.reportId||'');const status=String(b.status||'actioned');if(!['under_review','actioned','dismissed','escalated','closed'].includes(status))return NextResponse.json({error:'Invalid report status'},{status:400});const before=await s`select to_jsonb(mr) row from app.moderation_reports mr where id=${reportId}::uuid limit 1` as unknown as Array<{row:unknown}>;await s`update app.moderation_reports set status=${status},resolution=${String(b.resolution||'').trim()||null},assigned_to_person_id=${g.access!.personId}::uuid,updated_at=now() where id=${reportId}::uuid`;const actionType=String(b.actionType||'none');const targetPersonId=String(b.targetPersonId||'').trim()||null;if(actionType!=='none'&&targetPersonId){await s`insert into app.moderation_actions(report_id,target_person_id,action_type,starts_at,ends_at,reason,created_by_person_id) values (${reportId}::uuid,${targetPersonId}::uuid,${actionType},now(),${b.endsAt?String(b.endsAt):null}::timestamptz,${String(b.resolution||'Moderation action')},${g.access!.personId}::uuid)`;if(actionType==='temporary_suspension'||actionType==='permanent_ban')await s`update app.persons set account_status='suspended',updated_at=now() where id=${targetPersonId}::uuid`;if(actionType==='restore')await s`update app.persons set account_status='active',updated_at=now() where id=${targetPersonId}::uuid`;}const after=await s`select to_jsonb(mr) row from app.moderation_reports mr where id=${reportId}::uuid limit 1` as unknown as Array<{row:unknown}>;await s`insert into app.audit_logs(actor_person_id,action,object_type,object_id,before_data,after_data,reason) values (${g.access!.personId}::uuid,'trust.report.resolve','moderation_report',${reportId}::uuid,${JSON.stringify(before[0]?.row||{})}::jsonb,${JSON.stringify(after[0]?.row||{})}::jsonb,${String(b.resolution||'Moderation resolution')})`;return NextResponse.json({ok:true});}
return NextResponse.json({error:'Unknown action'},{status:400});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Trust action failed'},{status:400});}}
