-- ForeverPoints tamper-evidence + dispute/refund/correction workflow
create extension if not exists pgcrypto;

alter table app.foreverpoints_ledger
  add column if not exists ledger_sequence bigint generated by default as identity,
  add column if not exists previous_hash text,
  add column if not exists payload_hash text,
  add column if not exists chain_hash text,
  add column if not exists server_signature text,
  add column if not exists integrity_version integer not null default 1;

create unique index if not exists uq_foreverpoints_ledger_sequence on app.foreverpoints_ledger(ledger_sequence);
create unique index if not exists uq_foreverpoints_ledger_chain_hash on app.foreverpoints_ledger(chain_hash) where chain_hash is not null;

create or replace function app.foreverpoints_set_integrity()
returns trigger language plpgsql as $$
declare
  v_prev text;
  v_payload text;
begin
  perform pg_advisory_xact_lock(hashtext('togetherforever:foreverpoints:ledger'));

  select chain_hash into v_prev
  from app.foreverpoints_ledger
  where ledger_sequence < new.ledger_sequence
  order by ledger_sequence desc
  limit 1;

  new.previous_hash := coalesce(v_prev, repeat('0',64));
  v_payload := concat_ws('|',
    new.id::text,
    new.account_id::text,
    new.person_id::text,
    new.transaction_type,
    new.points_delta::text,
    coalesce(new.activity_type,''),
    coalesce(new.source_object_type,''),
    coalesce(new.source_object_id::text,''),
    coalesce(new.rule_id::text,''),
    coalesce(new.related_ledger_id::text,''),
    coalesce(new.idempotency_key,''),
    coalesce(new.description,''),
    coalesce(new.expires_at::text,''),
    coalesce(new.created_by_person_id::text,''),
    new.created_at::text,
    new.integrity_version::text
  );

  new.payload_hash := encode(digest(v_payload,'sha256'),'hex');
  new.chain_hash := encode(digest(new.previous_hash || '|' || new.payload_hash || '|' || coalesce(new.server_signature,''),'sha256'),'hex');
  return new;
end $$;

create or replace function app.foreverpoints_block_mutation()
returns trigger language plpgsql as $$
begin
  raise exception 'ForeverPoints ledger is append-only. Create a reversal/correction transaction instead.' using errcode='55000';
end $$;

drop trigger if exists trg_foreverpoints_integrity on app.foreverpoints_ledger;
create trigger trg_foreverpoints_integrity
before insert on app.foreverpoints_ledger
for each row execute function app.foreverpoints_set_integrity();

drop trigger if exists trg_foreverpoints_immutable_update on app.foreverpoints_ledger;
create trigger trg_foreverpoints_immutable_update
before update on app.foreverpoints_ledger
for each row execute function app.foreverpoints_block_mutation();

drop trigger if exists trg_foreverpoints_immutable_delete on app.foreverpoints_ledger;
create trigger trg_foreverpoints_immutable_delete
before delete on app.foreverpoints_ledger
for each row execute function app.foreverpoints_block_mutation();

create table if not exists app.foreverpoints_integrity_checkpoints (
  id uuid primary key default gen_random_uuid(),
  first_sequence bigint not null,
  last_sequence bigint not null,
  transaction_count bigint not null check (transaction_count >= 0),
  root_hash text not null,
  previous_checkpoint_hash text,
  checkpoint_hash text not null unique,
  external_anchor text,
  created_at timestamptz not null default now(),
  created_by_person_id uuid references app.persons(id) on delete set null,
  check (last_sequence >= first_sequence)
);

create table if not exists app.foreverpoints_cases (
  id uuid primary key default gen_random_uuid(),
  case_number text not null unique,
  person_id uuid not null references app.persons(id) on delete restrict,
  account_id uuid not null references app.foreverpoints_accounts(id) on delete restrict,
  original_ledger_id uuid references app.foreverpoints_ledger(id) on delete restrict,
  case_type text not null check (case_type in (
    'activity_disputed','missing_points','wrong_amount','incorrect_deduction','refund_request',
    'duplicate_transaction','failed_redemption','cancelled_activity','system_error','admin_error',
    'fraud_review','expiry_dispute','transfer_error','service_not_delivered','other'
  )),
  status text not null default 'submitted' check (status in (
    'submitted','acknowledged','under_review','evidence_requested','awaiting_user','awaiting_admin',
    'awaiting_approver','approved','partially_approved','rejected','corrected','reversed','refunded',
    'closed','reopened','escalated'
  )),
  subject text not null,
  description text not null,
  requested_points bigint,
  resolution_type text check (resolution_type is null or resolution_type in (
    'uphold','reverse','partial_correction','replace','refund','correction_credit','correction_debit',
    'goodwill_credit','waive_recovery','no_change'
  )),
  resolution_notes text,
  assigned_to_person_id uuid references app.persons(id) on delete set null,
  opened_at timestamptz not null default now(),
  resolved_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists app.foreverpoints_case_events (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references app.foreverpoints_cases(id) on delete cascade,
  event_type text not null,
  actor_person_id uuid references app.persons(id) on delete set null,
  note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists app.foreverpoints_case_evidence (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references app.foreverpoints_cases(id) on delete cascade,
  submitted_by_person_id uuid references app.persons(id) on delete set null,
  evidence_type text not null default 'note',
  external_url text,
  storage_key text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists app.foreverpoints_case_ledger_links (
  case_id uuid not null references app.foreverpoints_cases(id) on delete cascade,
  ledger_id uuid not null references app.foreverpoints_ledger(id) on delete restrict,
  link_type text not null check (link_type in ('original','reversal','refund','correction','replacement','recovery')),
  primary key (case_id, ledger_id)
);

create table if not exists app.foreverpoints_recovery_balances (
  account_id uuid primary key references app.foreverpoints_accounts(id) on delete cascade,
  recovery_points bigint not null default 0 check (recovery_points >= 0),
  reason_case_id uuid references app.foreverpoints_cases(id) on delete set null,
  updated_at timestamptz not null default now()
);

create or replace function app.verify_foreverpoints_chain()
returns table(ledger_sequence bigint, stored_hash text, expected_hash text, valid boolean)
language sql stable as $$
with ordered as (
  select l.*,
    lag(chain_hash) over(order by ledger_sequence) as prior_chain
  from app.foreverpoints_ledger l
), calc as (
  select o.ledger_sequence,
         o.chain_hash as stored_hash,
         encode(digest(
           coalesce(o.prior_chain, repeat('0',64)) || '|' || o.payload_hash || '|' || coalesce(o.server_signature,''),
           'sha256'
         ),'hex') as expected_hash
  from ordered o
)
select ledger_sequence, stored_hash, expected_hash, stored_hash = expected_hash
from calc
order by ledger_sequence;
$$;

insert into app.permissions (key,domain,action,description,is_sensitive) values
('foreverpoints.case.create','foreverpoints','case_create','Open a ForeverPoints dispute or correction case',false),
('foreverpoints.case.review','foreverpoints','case_review','Review ForeverPoints disputes and evidence',true),
('foreverpoints.case.resolve','foreverpoints','case_resolve','Resolve ForeverPoints disputes using compensating transactions',true),
('foreverpoints.adjust.approve','foreverpoints','adjust_approve','Approve sensitive or threshold-based ForeverPoints adjustments',true),
('foreverpoints.integrity.verify','foreverpoints','integrity_verify','Run and review ForeverPoints ledger integrity verification',true)
on conflict (key) do nothing;
