import {NextResponse} from 'next/server';
import {auth} from '../../../../lib/auth/server';
import {accessForAuthUser} from '../../../../lib/access';
import {db} from '../../../../lib/db';
type U={id:string};type S={user?:U|null;data?:{user?:U|null}|null};
const categories=['general','events','opportunities','welfare','critical'];const channels=['in_app','email','sms','whatsapp','push'];
async function me(){const raw=(await auth.getSession()) as unknown as S;const u=raw.user??raw.data?.user??null;if(!u?.id)return null;return accessForAuthUser(u.id)}
export async function GET(){const a=await me();if(!a||a.accountStatus!=='active')return NextResponse.json({error:'Unauthorized'},{status:401});const s=db();const rows=await s`select category,channel,enabled,consent_status,consented_at,withdrawn_at,updated_at from app.notification_preferences where person_id=${a.personId}::uuid order by category,channel` as unknown as Array<Record<string,unknown>>;return NextResponse.json({preferences:rows,categories,channels});}
export async function PUT(r:Request){const a=await me();if(!a||a.accountStatus!=='active')return NextResponse.json({error:'Unauthorized'},{status:401});const b=await r.json() as {category?:string;channel?:string;enabled?:boolean};const category=String(b.category||''),channel=String(b.channel||'');if(!categories.includes(category)||!channels.includes(channel))return NextResponse.json({error:'Invalid preference'},{status:400});if(category==='critical'&&channel==='in_app'&&b.enabled===false)return NextResponse.json({error:'Critical in-app notices cannot be disabled.'},{status:400});const enabled=b.enabled!==false;const consent=channel==='in_app'?'not_required':enabled?'granted':'withdrawn';const s=db();await s`insert into app.notification_preferences(person_id,category,channel,enabled,consent_status,consented_at,withdrawn_at) values(${a.personId}::uuid,${category},${channel},${enabled},${consent},case when ${enabled} then now() else null end,case when ${enabled} then null else now() end) on conflict(person_id,category,channel) do update set enabled=excluded.enabled,consent_status=excluded.consent_status,consented_at=case when excluded.enabled then now() else app.notification_preferences.consented_at end,withdrawn_at=case when excluded.enabled then null else now() end,updated_at=now()`;await s`insert into app.audit_logs(actor_person_id,action,object_type,after_data) values(${a.personId}::uuid,'notification.preference.update','notification_preference',${JSON.stringify({category,channel,enabled,consent})}::jsonb)`;return GET();}
