import { NextResponse } from 'next/server';
import { createHash,randomBytes } from 'crypto';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser,hasPermission } from '../../../../lib/access';
import { db } from '../../../../lib/db';
type SessionUser={id:string};type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')return {error:NextResponse.json({error:'Forbidden'},{status:403})};return {access};}
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
export async function GET(){const g=await gate();if(g.error)return g.error;const s=db();const positions=await s`select id::text,key,title,description,appointment_method,eligibility_policy,electorate_policy,term_months,is_active from app.governance_positions order by is_active desc,title`;const terms=await s`select ot.id::text,gp.title as position_title,p.full_name,mc.code as holder_code,ot.method_used,ot.starts_on,ot.ends_on,ot.status from app.office_terms ot join app.governance_positions gp on gp.id=ot.governance_position_id join app.persons p on p.id=ot.holder_person_id left join app.membership_codes mc on mc.person_id=p.id order by ot.starts_on desc`;const elections=await s`select e.id::text,e.title,e.election_type,e.ballot_mode,e.result_method,e.status,e.nomination_opens_at,e.nomination_closes_at,e.voting_opens_at,e.voting_closes_at,e.electorate_policy,gp.title as position_title from app.elections e left join app.governance_positions gp on gp.id=e.governance_position_id order by e.created_at desc`;const candidates=await s`select ec.id::text,ec.election_id::text,p.full_name,mc.code as membership_code,ec.statement,ec.status from app.election_candidates ec join app.persons p on p.id=ec.person_id left join app.membership_codes mc on mc.person_id=p.id order by ec.created_at`;return NextResponse.json({positions,terms,elections,candidates,canConfigure:hasPermission(g.access!,'governance.configure'),canVote:hasPermission(g.access!,'governance.vote')});}
export async function POST(request:Request){const g=await gate();if(g.error)return g.error;const b=await request.json() as Record<string,unknown>;const action=String(b.action||'');const s=db();try{
 if(action==='position.create'){if(!hasPermission(g.access!,'governance.configure'))return NextResponse.json({error:'Forbidden'},{status:403});const title=String(b.title||'').trim();const key=String(b.key||title.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')).slice(0,64);const method=String(b.method||'selection');if(!title)return NextResponse.json({error:'Title required'},{status:400});await s`insert into app.governance_positions(key,title,description,appointment_method,eligibility_policy,electorate_policy,term_months,is_active) values (${key},${title},${String(b.description||'').trim()||null},${method},${JSON.stringify(b.eligibility||{})}::jsonb,${JSON.stringify(b.electorate||{relationship_prefixes:['M']})}::jsonb,${Number(b.termMonths||24)},true)`;return NextResponse.json({ok:true},{status:201});}
 if(action==='election.create'){if(!hasPermission(g.access!,'governance.configure'))return NextResponse.json({error:'Forbidden'},{status:403});const positionId=String(b.positionId||'');const title=String(b.title||'').trim();if(!positionId||!title)return NextResponse.json({error:'Position and title required'},{status:400});await s`insert into app.elections(governance_position_id,title,election_type,nomination_opens_at,nomination_closes_at,voting_opens_at,voting_closes_at,electorate_policy,eligibility_policy,ballot_mode,result_method,quorum_rule,status) values (${positionId}::uuid,${title},${String(b.electionType||'election')},${b.nominationOpens?String(b.nominationOpens):null}::timestamptz,${b.nominationCloses?String(b.nominationCloses):null}::timestamptz,${b.votingOpens?String(b.votingOpens):null}::timestamptz,${b.votingCloses?String(b.votingCloses):null}::timestamptz,${JSON.stringify(b.electorate||{relationship_prefixes:['M']})}::jsonb,${JSON.stringify(b.eligibility||{relationship_prefixes:['M']})}::jsonb,${String(b.ballotMode||'secret')},${String(b.resultMethod||'plurality')},${JSON.stringify(b.quorum||{})}::jsonb,'nominations')`;return NextResponse.json({ok:true},{status:201});}
 if(action==='candidate.nominate'){const electionId=String(b.electionId||'');const candidateCode=String(b.candidateCode||'').trim();if(!electionId||!candidateCode)return NextResponse.json({error:'Election and candidate membership code required'},{status:400});const candidate=await s`select person_id::text from app.membership_codes where upper(code)=upper(${candidateCode}) limit 1` as unknown as Array<{person_id:string}>;if(!candidate[0])return NextResponse.json({error:'Candidate not found'},{status:404});await s`insert into app.election_candidates(election_id,person_id,nominated_by_person_id,statement,status) values (${electionId}::uuid,${candidate[0].person_id}::uuid,${g.access!.personId}::uuid,${String(b.statement||'').trim()||null},'nominated') on conflict(election_id,person_id) do nothing`;return NextResponse.json({ok:true},{status:201});}
 if(action==='vote'){if(!hasPermission(g.access!,'governance.vote'))return NextResponse.json({error:'Forbidden'},{status:403});const electionId=String(b.electionId||'');const candidateId=String(b.candidateId||'');const e=await s`select electorate_policy,status,voting_opens_at,voting_closes_at from app.elections where id=${electionId}::uuid limit 1` as unknown as Array<{electorate_policy:any;status:string;voting_opens_at:string|null;voting_closes_at:string|null}>;if(!e[0]||e[0].status!=='voting')return NextResponse.json({error:'Election is not open for voting.'},{status:400});const allowed=Array.isArray(e[0].electorate_policy?.relationship_prefixes)?e[0].electorate_policy.relationship_prefixes:['M'];if(!allowed.includes(g.access!.relationshipPrefix))return NextResponse.json({error:'You are not in the configured electorate.'},{status:403});const valid=await s`select id::text from app.election_candidates where id=${candidateId}::uuid and election_id=${electionId}::uuid and status in ('eligible','approved','nominated') limit 1` as unknown as Array<{id:string}>;if(!valid[0])return NextResponse.json({error:'Candidate is not valid for this election.'},{status:400});const receiptHash=hash('receipt:'+randomBytes(32).toString('hex'));const ballotHash=hash('ballot:'+randomBytes(32).toString('hex'));await s`select app.cast_election_ballot(${electionId}::uuid,${g.access!.personId}::uuid,${candidateId}::uuid,${receiptHash},${ballotHash})`;return NextResponse.json({ok:true,receipt:receiptHash.slice(0,12)},{status:201});}
 if(action==='office.assign'){if(!hasPermission(g.access!,'governance.configure'))return NextResponse.json({error:'Forbidden'},{status:403});const positionId=String(b.positionId||'');const holderCode=String(b.holderCode||'').trim();const holder=await s`select person_id::text from app.membership_codes where upper(code)=upper(${holderCode}) limit 1` as unknown as Array<{person_id:string}>;if(!holder[0])return NextResponse.json({error:'Holder not found'},{status:404});await s`insert into app.office_terms(governance_position_id,holder_person_id,method_used,starts_on,ends_on,status,notes) values (${positionId}::uuid,${holder[0].person_id}::uuid,${String(b.method||'appointment')},${String(b.startsOn||new Date().toISOString().slice(0,10))}::date,${b.endsOn?String(b.endsOn):null}::date,'active',${String(b.notes||'').trim()||null})`;return NextResponse.json({ok:true},{status:201});}
 return NextResponse.json({error:'Unknown action'},{status:400});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Governance action failed'},{status:400});}}
