import {NextResponse} from 'next/server';
import {auth} from '../../../../lib/auth/server';
import {accessForAuthUser,hasPermission} from '../../../../lib/access';
import {db} from '../../../../lib/db';
import {requireStepUp} from '../../../../lib/security/step-up';
type U={id:string};type S={user?:U|null;data?:{user?:U|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as S;const u=raw.user??raw.data?.user??null;if(!u?.id)return {e:NextResponse.json({error:'Unauthorized'},{status:401})};const a=await accessForAuthUser(u.id);if(!a||a.accountStatus!=='active'||!hasPermission(a,'opportunities.review'))return {e:NextResponse.json({error:'Forbidden'},{status:403})};return {a};}
export async function GET(){const g=await gate();if(g.e)return g.e;const s=db();const rows=await s`select oa.id::text,oa.status,oa.message,oa.created_at,o.title opportunity_title,o.organization_name,p.full_name,mc.code,(select json_agg(json_build_object('from',e.from_status,'to',e.to_status,'note',e.note,'at',e.created_at) order by e.created_at) from app.opportunity_application_events e where e.application_id=oa.id) events,(select json_agg(json_build_object('id',i.id,'starts_at',i.starts_at,'ends_at',i.ends_at,'status',i.status,'meeting_url',i.meeting_url,'location_text',i.location_text) order by i.starts_at desc) from app.opportunity_interviews i where i.application_id=oa.id) interviews from app.opportunity_applications oa join app.opportunities o on o.id=oa.opportunity_id join app.persons p on p.id=oa.applicant_person_id left join app.membership_codes mc on mc.person_id=p.id order by oa.updated_at desc limit 200`;return NextResponse.json({applications:rows});}
export async function POST(r:Request){const g=await gate();if(g.e)return g.e;const step=await requireStepUp(g.a!.personId,'opportunities.review');if(step)return NextResponse.json(step,{status:428});const b=await r.json() as Record<string,unknown>;const action=String(b.action||'');const s=db();if(action==='status'){const id=String(b.applicationId||''),to=String(b.status||'');if(!['reviewing','shortlisted','interview','accepted','rejected','closed'].includes(to))return NextResponse.json({error:'Invalid status'},{status:400});const cur=await s`select status from app.opportunity_applications where id=${id}::uuid limit 1` as unknown as Array<{status:string}>;if(!cur[0])return NextResponse.json({error:'Application not found'},{status:404});await s`update app.opportunity_applications set status=${to},updated_at=now() where id=${id}::uuid`;await s`insert into app.opportunity_application_events(application_id,from_status,to_status,note,actor_person_id) values(${id}::uuid,${cur[0].status},${to},${String(b.note||'').trim()||null},${g.a!.personId}::uuid)`;return NextResponse.json({ok:true,status:to});}
if(action==='interview'){const id=String(b.applicationId||''),starts=String(b.startsAt||'');if(!starts)return NextResponse.json({error:'startsAt required'},{status:400});const rows=await s`insert into app.opportunity_interviews(application_id,starts_at,ends_at,timezone,meeting_url,location_text,interviewer_person_id,notes,created_by_person_id) values(${id}::uuid,${starts}::timestamptz,${b.endsAt?String(b.endsAt):null}::timestamptz,${String(b.timezone||'UTC')},${String(b.meetingUrl||'').trim()||null},${String(b.locationText||'').trim()||null},${g.a!.personId}::uuid,${String(b.notes||'').trim()||null},${g.a!.personId}::uuid) returning id::text` as unknown as Array<{id:string}>;await s`update app.opportunity_applications set status='interview',updated_at=now() where id=${id}::uuid`;return NextResponse.json({ok:true,id:rows[0]?.id},{status:201});}
return NextResponse.json({error:'Unknown action'},{status:400});}
