import { NextResponse } from 'next/server';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser,hasPermission } from '../../../../lib/access';
import { db } from '../../../../lib/db';

type SessionUser={id:string};type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')return {error:NextResponse.json({error:'Forbidden'},{status:403})};return {access};}
export async function GET(){const g=await gate();if(g.error)return g.error;const s=db();const profile=await s`select id::text,can_mentor,seeking_mentor,domains,goals,availability,preferred_mode,bio,is_active from app.mentorship_profiles where person_id=${g.access!.personId}::uuid limit 1` as unknown as unknown[];const requests=await s`select id::text,domains,goals,status,created_at from app.mentorship_requests where mentee_person_id=${g.access!.personId}::uuid order by created_at desc` as unknown as unknown[];const scholarships=await s`select id::text,title,description,eligibility_policy,opens_at,closes_at,award_amount,currency,status from app.scholarship_programs where status<>'archived' order by created_at desc` as unknown as unknown[];const applications=await s`select id::text,scholarship_program_id::text,status,submitted_at from app.scholarship_applications where applicant_person_id=${g.access!.personId}::uuid order by created_at desc` as unknown as unknown[];return NextResponse.json({profile:profile[0]||null,requests,scholarships,applications,canManageMentorship:hasPermission(g.access!,'mentorship.manage'),canManageScholarships:hasPermission(g.access!,'scholarships.manage')});}
export async function POST(request:Request){const g=await gate();if(g.error)return g.error;const b=await request.json() as Record<string,unknown>;const action=String(b.action||'');const s=db();try{
 if(action==='mentorship.profile'){if(!hasPermission(g.access!,'mentorship.manage_own'))return NextResponse.json({error:'Forbidden'},{status:403});const domains=Array.isArray(b.domains)?b.domains.map(String):[];const goals=Array.isArray(b.goals)?b.goals.map(String):[];await s`insert into app.mentorship_profiles(person_id,can_mentor,seeking_mentor,domains,goals,availability,preferred_mode,bio,is_active) values (${g.access!.personId}::uuid,${Boolean(b.canMentor)},${Boolean(b.seekingMentor)},${domains}::text[],${goals}::text[],${String(b.availability||'').trim()||null},${String(b.preferredMode||'').trim()||null},${String(b.bio||'').trim()||null},true) on conflict(person_id) do update set can_mentor=excluded.can_mentor,seeking_mentor=excluded.seeking_mentor,domains=excluded.domains,goals=excluded.goals,availability=excluded.availability,preferred_mode=excluded.preferred_mode,bio=excluded.bio,is_active=true,updated_at=now()`;return NextResponse.json({ok:true});}
 if(action==='mentorship.request'){if(!hasPermission(g.access!,'mentorship.manage_own'))return NextResponse.json({error:'Forbidden'},{status:403});const domains=Array.isArray(b.domains)?b.domains.map(String):[];await s`insert into app.mentorship_requests(mentee_person_id,domains,goals,status) values (${g.access!.personId}::uuid,${domains}::text[],${String(b.goals||'').trim()},'open')`;return NextResponse.json({ok:true},{status:201});}
 if(action==='scholarship.apply'){if(!hasPermission(g.access!,'scholarships.apply'))return NextResponse.json({error:'Forbidden'},{status:403});const programId=String(b.programId||'');if(!programId)return NextResponse.json({error:'programId required'},{status:400});await s`insert into app.scholarship_applications(scholarship_program_id,applicant_person_id,sponsored_by_person_id,application_data,status,submitted_at) values (${programId}::uuid,${g.access!.personId}::uuid,${g.access!.relationshipPrefix==='M'?null:g.access!.personId}::uuid,${JSON.stringify({statement:String(b.statement||'')})}::jsonb,'submitted',now()) on conflict(scholarship_program_id,applicant_person_id) do update set application_data=excluded.application_data,status='submitted',submitted_at=now(),updated_at=now()`;return NextResponse.json({ok:true},{status:201});}
 if(action==='scholarship.create'){if(!hasPermission(g.access!,'scholarships.manage'))return NextResponse.json({error:'Forbidden'},{status:403});await s`insert into app.scholarship_programs(title,description,eligibility_policy,opens_at,closes_at,award_amount,currency,status,created_by_person_id) values (${String(b.title||'').trim()},${String(b.description||'').trim()||null},${JSON.stringify(b.eligibility||{relationship_prefixes:['M','S','D','GS','GD']})}::jsonb,${b.opensAt?String(b.opensAt):null}::timestamptz,${b.closesAt?String(b.closesAt):null}::timestamptz,${b.amount?Number(b.amount):null},${String(b.currency||'PKR')},'open',${g.access!.personId}::uuid)`;return NextResponse.json({ok:true},{status:201});}
 return NextResponse.json({error:'Unknown action'},{status:400});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to save'},{status:400});}}
