import { NextResponse } from 'next/server';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser,hasPermission } from '../../../../lib/access';
import { db } from '../../../../lib/db';

type SessionUser={id:string};type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')return {error:NextResponse.json({error:'Forbidden'},{status:403})};return {access};}

export async function POST(request:Request){const g=await gate();if(g.error)return g.error;const b=await request.json() as {action?:string;objectId?:string;message?:string;amount?:number|string;currency?:string;reference?:string;evidenceUrl?:string;guestCount?:number};if(!b.action||!b.objectId)return NextResponse.json({error:'action and objectId are required'},{status:400});const s=db();try{
 if(b.action==='event.register'){
   const event=await s`select id::text,capacity,registration_deadline,status from app.events where id=${b.objectId}::uuid and status in ('approved','ignited') limit 1` as unknown as Array<{id:string;capacity:number|null;registration_deadline:string|null;status:string}>;
   if(!event[0])return NextResponse.json({error:'Event unavailable'},{status:404});
   if(event[0].registration_deadline&&new Date(event[0].registration_deadline).getTime()<Date.now())return NextResponse.json({error:'Registration is closed.'},{status:409});
   const guests=Math.max(0,Math.min(10,Number(b.guestCount||0)));
   const active=await s`select coalesce(sum(1+guest_count),0)::int seats from app.event_registrations where event_id=${b.objectId}::uuid and status in ('registered','attended')` as unknown as Array<{seats:number}>;
   const seatsUsed=active[0]?.seats||0;const requested=1+guests;
   let status='registered',waitlistPosition:null|number=null;
   if(event[0].capacity!==null&&seatsUsed+requested>event[0].capacity){const q=await s`select coalesce(max(waitlist_position),0)::int n from app.event_registrations where event_id=${b.objectId}::uuid and status='waitlisted'` as unknown as Array<{n:number}>;status='waitlisted';waitlistPosition=(q[0]?.n||0)+1;}
   await s`insert into app.event_registrations(event_id,person_id,status,guest_count,waitlist_position,updated_at) values (${b.objectId}::uuid,${g.access!.personId}::uuid,${status},${guests},${waitlistPosition},now()) on conflict(event_id,person_id) do update set status=excluded.status,guest_count=excluded.guest_count,waitlist_position=excluded.waitlist_position,updated_at=now()`;
   return NextResponse.json({ok:true,status,waitlistPosition});
 }
 if(b.action==='event.cancel'){await s`update app.event_registrations set status='cancelled',waitlist_position=null,updated_at=now() where event_id=${b.objectId}::uuid and person_id=${g.access!.personId}::uuid`;return NextResponse.json({ok:true,status:'cancelled'});}
 if(b.action==='opportunity.apply'){if(!hasPermission(g.access!,'opportunities.apply'))return NextResponse.json({error:'Forbidden'},{status:403});await s`insert into app.opportunity_applications(opportunity_id,applicant_person_id,message,status) values (${b.objectId}::uuid,${g.access!.personId}::uuid,${b.message?.trim()||null},'submitted') on conflict(opportunity_id,applicant_person_id) do update set message=excluded.message,status='submitted',updated_at=now()`;return NextResponse.json({ok:true,status:'submitted'});}
 if(b.action==='listing.respond'){await s`insert into app.listing_responses(listing_id,responder_person_id,message,offered_amount,currency,status) values (${b.objectId}::uuid,${g.access!.personId}::uuid,${b.message?.trim()||'Interested'},${b.amount?Number(b.amount):null},${b.currency||'PKR'},'open')`;return NextResponse.json({ok:true,status:'open'});}
 if(b.action==='transaction.mark_paid'){if(!hasPermission(g.access!,'transactions.mark_paid'))return NextResponse.json({error:'Forbidden'},{status:403});const r=await s`update app.transactions set status='awaiting_receiver_confirmation',sender_marked_paid_at=now(),external_reference=coalesce(${b.reference?.trim()||null},external_reference),evidence_url=coalesce(${b.evidenceUrl?.trim()||null},evidence_url),updated_at=now() where id=${b.objectId}::uuid and payer_person_id=${g.access!.personId}::uuid and status in ('pending','arranged') returning id::text,status` as unknown as unknown[];if(!r.length)return NextResponse.json({error:'Transaction is not eligible or does not belong to you.'},{status:403});return NextResponse.json({ok:true,status:'awaiting_receiver_confirmation'});}
 if(b.action==='transaction.confirm_received'){if(!hasPermission(g.access!,'payments.confirm_receipt'))return NextResponse.json({error:'Forbidden'},{status:403});const r=await s`update app.transactions set status='completed',receiver_confirmed_at=now(),completed_at=now(),updated_at=now() where id=${b.objectId}::uuid and receiver_person_id=${g.access!.personId}::uuid and status in ('sender_marked_paid','awaiting_receiver_confirmation','received') returning id::text,status` as unknown as unknown[];if(!r.length)return NextResponse.json({error:'Transaction is not eligible or you are not the receiver.'},{status:403});return NextResponse.json({ok:true,status:'completed'});}
 return NextResponse.json({error:'Unknown action'},{status:400});
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Action failed'},{status:400});}}
