import {NextResponse} from 'next/server';
import {auth} from '../../../../lib/auth/server';
import {accessForAuthUser,hasPermission} from '../../../../lib/access';
import {db} from '../../../../lib/db';
import {requireStepUp} from '../../../../lib/security/step-up';

type U={id:string};type S={user?:U|null;data?:{user?:U|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as S;const u=raw.user??raw.data?.user??null;if(!u?.id)return {e:NextResponse.json({error:'Unauthorized'},{status:401})};const a=await accessForAuthUser(u.id);if(!hasPermission(a,'roles.update'))return {e:NextResponse.json({error:'Forbidden'},{status:403})};return {a};}
const allowedScopes=new Set(['space','chapter','committee','board','family','event']);
export async function GET(){const g=await gate();if(g.e)return g.e;const s=db();const assignments=await s`select pr.id::text,pr.person_id::text,pr.role_id::text,pr.scope_type,pr.scope_id::text,pr.starts_at,pr.ends_at,p.full_name,mc.code membership_code,r.name role_name,r.key role_key,sp.name scope_name from app.person_roles pr join app.persons p on p.id=pr.person_id left join app.membership_codes mc on mc.person_id=p.id join app.roles r on r.id=pr.role_id left join app.spaces sp on pr.scope_type='space' and sp.id=pr.scope_id where coalesce(pr.scope_type,'global')<>'global' and pr.starts_at<=now() and (pr.ends_at is null or pr.ends_at>now()) order by pr.created_at desc`;const roles=await s`select id::text,key,name from app.roles where is_active=true order by name`;const spaces=await s`select id::text,space_type,name from app.spaces where is_active=true order by name`;return NextResponse.json({assignments,roles,spaces,scopeTypes:[...allowedScopes]});}
export async function POST(req:Request){const g=await gate();if(g.e)return g.e;const step=await requireStepUp(g.a!.personId,'rbac.manage');if(step)return NextResponse.json(step,{status:428});const b=await req.json() as Record<string,unknown>;const memberCode=String(b.memberCode||'').trim(),roleId=String(b.roleId||''),scopeType=String(b.scopeType||''),scopeId=String(b.scopeId||'');if(!memberCode||!roleId||!allowedScopes.has(scopeType)||!scopeId)return NextResponse.json({error:'Member, role, scope type and scope are required.'},{status:400});const s=db();const person=await s`select person_id::text from app.membership_codes where upper(code)=upper(${memberCode}) limit 1` as unknown as Array<{person_id:string}>;if(!person[0])return NextResponse.json({error:'Member not found.'},{status:404});try{const rows=await s`insert into app.person_roles(person_id,role_id,scope_type,scope_id,starts_at,ends_at,assigned_by_person_id) values(${person[0].person_id}::uuid,${roleId}::uuid,${scopeType},${scopeId}::uuid,now(),${b.endsAt?String(b.endsAt):null}::timestamptz,${g.a!.personId}::uuid) returning id::text` as unknown as Array<{id:string}>;await s`insert into app.audit_logs(actor_person_id,action,object_type,object_id,after_data) values(${g.a!.personId}::uuid,'role.assign_scoped','person_role',${rows[0].id}::uuid,${JSON.stringify({personId:person[0].person_id,roleId,scopeType,scopeId})}::jsonb)`;return NextResponse.json({ok:true,id:rows[0].id},{status:201});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to assign scoped role'},{status:400});}}
export async function DELETE(req:Request){const g=await gate();if(g.e)return g.e;const step=await requireStepUp(g.a!.personId,'rbac.manage');if(step)return NextResponse.json(step,{status:428});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Assignment id required'},{status:400});const s=db();const before=await s`select id::text,person_id::text,role_id::text,scope_type,scope_id::text from app.person_roles where id=${id}::uuid and coalesce(scope_type,'global')<>'global' limit 1` as unknown as Array<Record<string,unknown>>;if(!before[0])return NextResponse.json({error:'Scoped assignment not found'},{status:404});await s`update app.person_roles set ends_at=now() where id=${id}::uuid`;await s`insert into app.audit_logs(actor_person_id,action,object_type,object_id,before_data) values(${g.a!.personId}::uuid,'role.revoke_scoped','person_role',${id}::uuid,${JSON.stringify(before[0])}::jsonb)`;return NextResponse.json({ok:true});}
