import {NextResponse} from 'next/server';
import {auth} from '../../../../lib/auth/server';
import {accessForAuthUser,hasPermission} from '../../../../lib/access';
import {db} from '../../../../lib/db';
import {requireStepUp} from '../../../../lib/security/step-up';

type U={id:string};
type S={user?:U|null;data?:{user?:U|null}|null};
type CaseRow={id:string;case_number:string;beneficiary_person_id:string|null;requested_by_person_id:string|null;assigned_to_person_id:string|null;category:string;urgency:string;requested_amount:number|null;approved_amount:number|null;currency:string;status:string;confidentiality:'restricted'|'committee'|'board';summary:string|null;decision_notes:string|null;created_at:string;beneficiary_name:string|null;beneficiary_code:string|null;has_grant:boolean};

async function gate(){const raw=(await auth.getSession()) as unknown as S;const u=raw.user??raw.data?.user??null;if(!u?.id)return {e:NextResponse.json({error:'Unauthorized'},{status:401})};const a=await accessForAuthUser(u.id);if(!a||a.accountStatus!=='active'||!(hasPermission(a,'welfare.read')||hasPermission(a,'welfare.manage')||hasPermission(a,'welfare.confidential.read')||hasPermission(a,'welfare.board.read')))return {e:NextResponse.json({error:'Forbidden'},{status:403})};return {a};}

function canSeeFull(row:CaseRow,personId:string,permissions:string[]){if(row.has_grant||row.beneficiary_person_id===personId||row.requested_by_person_id===personId||row.assigned_to_person_id===personId)return true;if(permissions.includes('welfare.manage'))return true;if(row.confidentiality==='board')return permissions.includes('welfare.board.read');if(row.confidentiality==='committee')return permissions.includes('welfare.confidential.read')||permissions.includes('welfare.board.read');return permissions.includes('welfare.confidential.read')||permissions.includes('welfare.board.read');}

export async function GET(){const g=await gate();if(g.e)return g.e;const s=db();const rows=await s`select wc.id::text,wc.case_number,wc.beneficiary_person_id::text,wc.requested_by_person_id::text,wc.assigned_to_person_id::text,wc.category,wc.urgency,wc.requested_amount,wc.approved_amount,wc.currency,wc.status,wc.confidentiality,wc.summary,wc.decision_notes,wc.created_at,p.full_name beneficiary_name,mc.code beneficiary_code,exists(select 1 from app.welfare_case_access_grants ag where ag.case_id=wc.id and ag.person_id=${g.a!.personId}::uuid and ag.revoked_at is null and (ag.expires_at is null or ag.expires_at>now())) has_grant from app.welfare_cases wc left join app.persons p on p.id=wc.beneficiary_person_id left join app.membership_codes mc on mc.person_id=p.id order by wc.created_at desc limit 200` as unknown as CaseRow[];const approvals=await s`select wa.id::text,wa.case_id::text,wa.approval_stage,wa.decision,wa.approved_amount,wa.notes,wa.decided_at,p.full_name decided_by from app.welfare_case_approvals wa join app.persons p on p.id=wa.decided_by_person_id order by wa.decided_at desc limit 300`;const permissions=g.a!.permissions;const cases=rows.map(r=>{const full=canSeeFull(r,g.a!.personId,permissions);return full?{...r,access:'full'}:{id:r.id,case_number:r.case_number,category:r.category,urgency:r.urgency,requested_amount:r.requested_amount,approved_amount:r.approved_amount,currency:r.currency,status:r.status,confidentiality:r.confidentiality,created_at:r.created_at,beneficiary_name:'Confidential',beneficiary_code:null,summary:null,decision_notes:null,access:'redacted'};});return NextResponse.json({cases,approvals,permissions:{canManage:hasPermission(g.a!,'welfare.manage'),canCommittee:hasPermission(g.a!,'welfare.confidential.read'),canBoard:hasPermission(g.a!,'welfare.board.read')}});}

export async function POST(req:Request){const g=await gate();if(g.e)return g.e;const b=await req.json() as Record<string,unknown>;const action=String(b.action||'');const s=db();if(action==='approve'){if(!hasPermission(g.a!,'welfare.manage'))return NextResponse.json({error:'Forbidden'},{status:403});const stage=String(b.stage||'committee'),decision=String(b.decision||'approved');if(!['committee','board'].includes(stage)||!['approved','partially_approved','rejected'].includes(decision))return NextResponse.json({error:'Invalid approval decision'},{status:400});if(stage==='committee'&&!hasPermission(g.a!,'welfare.confidential.read')&&!hasPermission(g.a!,'welfare.board.read'))return NextResponse.json({error:'Committee-level access required'},{status:403});if(stage==='board'&&!hasPermission(g.a!,'welfare.board.read'))return NextResponse.json({error:'Board-level access required'},{status:403});const step=await requireStepUp(g.a!.personId,'welfare.approval');if(step)return NextResponse.json(step,{status:428});const caseId=String(b.caseId||''),amount=b.approvedAmount==null?null:Number(b.approvedAmount),notes=String(b.notes||'').trim()||null;if(!caseId)return NextResponse.json({error:'caseId required'},{status:400});if(amount!=null&&amount<0)return NextResponse.json({error:'Invalid approved amount'},{status:400});const status=decision==='approved'?'approved':decision==='partially_approved'?'partially_approved':'rejected';const inserted=await s`insert into app.welfare_case_approvals(case_id,approval_stage,decision,approved_amount,notes,decided_by_person_id) values(${caseId}::uuid,${stage},${decision},${amount},${notes},${g.a!.personId}::uuid) returning id::text` as unknown as Array<{id:string}>;await s`update app.welfare_cases set status=${status},approved_amount=case when ${decision}='rejected' then approved_amount else coalesce(${amount},approved_amount) end,decision_notes=coalesce(${notes},decision_notes),assigned_to_person_id=${g.a!.personId}::uuid,updated_at=now() where id=${caseId}::uuid`;await s`insert into app.welfare_case_events(case_id,event_type,amount,currency,notes,actor_person_id) select id,${'approval_'+stage+'_'+decision},${amount},currency,${notes},${g.a!.personId}::uuid from app.welfare_cases where id=${caseId}::uuid`;return NextResponse.json({ok:true,id:inserted[0]?.id});}
if(action==='grant'){if(!hasPermission(g.a!,'welfare.board.read')&&!hasPermission(g.a!,'welfare.manage'))return NextResponse.json({error:'Forbidden'},{status:403});const step=await requireStepUp(g.a!.personId,'welfare.access');if(step)return NextResponse.json(step,{status:428});const caseId=String(b.caseId||''),membershipCode=String(b.membershipCode||'').trim(),level=String(b.accessLevel||'summary');if(!caseId||!membershipCode||!['summary','full','finance'].includes(level))return NextResponse.json({error:'caseId, membershipCode and valid accessLevel required'},{status:400});const person=await s`select person_id::text from app.membership_codes where upper(code)=upper(${membershipCode}) limit 1` as unknown as Array<{person_id:string}>;if(!person[0])return NextResponse.json({error:'Member not found'},{status:404});await s`insert into app.welfare_case_access_grants(case_id,person_id,access_level,granted_by_person_id,expires_at) values(${caseId}::uuid,${person[0].person_id}::uuid,${level},${g.a!.personId}::uuid,${b.expiresAt?String(b.expiresAt):null}::timestamptz) on conflict(case_id,person_id,access_level) do update set revoked_at=null,granted_at=now(),granted_by_person_id=excluded.granted_by_person_id,expires_at=excluded.expires_at`;return NextResponse.json({ok:true});}
return NextResponse.json({error:'Unknown action'},{status:400});}
