import Link from 'next/link';
import { redirect } from 'next/navigation';
import { Shield, Users, CalendarDays, BriefcaseBusiness, Store, HeartHandshake, Landmark, LockKeyhole, CircleCheckBig, Images, Building2, MessageCircle, Coins, Baby, Search, Mail, Network as NetworkIcon, GraduationCap, ReceiptText, Plus, UserRound } from 'lucide-react';
import { auth } from '../../lib/auth/server';
import { accessForAuthUser, hasPermission } from '../../lib/access';
import { db } from '../../lib/db';
import { SignOutButton } from './sign-out-button';

export const dynamic='force-dynamic';
type SessionUser={id:string;name?:string|null;email?:string|null};type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
const modules=[
 {slug:'events',name:'Events',text:'Reunions, talks, gatherings and member suggestions.',icon:CalendarDays,table:'events'},
 {slug:'opportunities',name:'Jobs & Business',text:'Jobs, internships, business opportunities and projects.',icon:BriefcaseBusiness,table:'opportunities'},
 {slug:'marketplace',name:'Marketplace',text:'General, land, vehicles, gold, digital assets and software.',icon:Store,table:'listings'},
 {slug:'fundraising',name:'Fundraising & Causes',text:'Crowdfunding suggestions, approved causes and welfare.',icon:HeartHandshake,table:'campaigns'},
 {slug:'gallery',name:'Gallery & Media',text:'Albums plus Google Drive, OneDrive and SharePoint links.',icon:Images,table:'media_albums'},
 {slug:'businesses',name:'Member Businesses',text:'Businesses, services, benefits and trusted providers.',icon:Building2,table:'businesses'},
 {slug:'family-life',name:'Family Life',text:'Matrimonial, playdates, tuition, travel and family support.',icon:Baby,table:'family_requests'},
 {slug:'community',name:'Community',text:'Ask the Network, needs, offers and updates.',icon:MessageCircle,table:'posts'},
];
export default async function NetworkPage(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)redirect('/auth/sign-in');const access=await accessForAuthUser(user.id);if(!access)return <Pending user={user}/>;if(access.accountStatus!=='active')return <main className="min-h-screen bg-[#06150d] px-4 py-10 text-white"><div className="mx-auto max-w-3xl rounded-[2rem] border border-white/10 bg-white/[0.04] p-8"><Shield className="h-10 w-10 text-amber-300"/><h1 className="mt-5 text-3xl font-semibold">Membership awaiting activation</h1><p className="mt-3 text-white/60">{access.fullName} · {access.membershipCode||'Membership code pending'} · Status: {access.accountStatus}</p><div className="mt-7"><SignOutButton/></div></div></main>;
 const sql=db();const counts=await sql`select (select count(*)::int from app.events where status<>'archived') events,(select count(*)::int from app.opportunities where status<>'archived') opportunities,(select count(*)::int from app.listings where status<>'archived') listings,(select count(*)::int from app.campaigns where status<>'archived') campaigns,(select count(*)::int from app.media_albums where status<>'archived') media_albums,(select count(*)::int from app.businesses where verification_status<>'suspended') businesses,(select count(*)::int from app.family_requests where status<>'archived') family_requests,(select count(*)::int from app.posts where status<>'archived') posts,(select count(*)::int from app.foreverpoints_cases where person_id=${access.personId}::uuid and status not in ('closed','rejected')) open_points_cases,(select count(*)::int from app.notifications where person_id=${access.personId}::uuid and read_at is null) unread_notifications` as unknown as Array<Record<string,number>>;const c=counts[0]||{};const canAdmin=['members.read','roles.read','events.approve','fundraising.manage','marketplace.moderate','opportunities.moderate','family.verify','governance.configure','foreverpoints.case.review','scholarships.manage','trust.moderate','features.manage'].some(p=>hasPermission(access,p));
 return <main className="min-h-screen bg-[#06150d] pb-24 text-white md:pb-8"><div className="sticky top-0 z-40 border-b border-white/10 bg-[#06150d]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><Link href="/" className="flex items-center gap-3"><Shield className="h-9 w-9 text-amber-300"/><div><div className="font-bold">Together Forever Network</div><div className="text-xs text-white/50">{access.membershipCode}</div></div></Link><div className="flex items-center gap-2"><Link href="/network/search" className="hidden rounded-lg border border-white/10 px-3 py-2 text-xs text-white/60 sm:inline">Search</Link>{canAdmin&&<Link href="/admin" className="hidden rounded-lg border border-white/10 px-3 py-2 text-xs text-white/60 sm:inline">Admin</Link>}<SignOutButton/></div></div></div>
 <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><section className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-white/[0.07] to-transparent p-7 sm:p-10"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1 text-xs text-emerald-200"><CircleCheckBig className="h-3.5 w-3.5"/> Verified network identity</div><h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">Welcome, {access.fullName}</h1><p className="mt-3 text-white/55">{access.membershipCode} · {access.roles.length?access.roles.join(' · '):'Network member'}</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><Link href="/network/foreverpoints" className="rounded-2xl border border-amber-300/20 bg-amber-300/5 px-4 py-3"><div className="flex items-center gap-2 text-sm font-semibold"><Coins className="h-4 w-4 text-amber-300"/> ForeverPoints</div><div className="mt-1 text-[10px] text-white/45">{c.open_points_cases||0} open cases</div></Link><Link href="/network/inbox" className="rounded-2xl border border-white/10 bg-black/20 px-4 py-3"><div className="flex items-center gap-2 text-sm font-semibold"><Mail className="h-4 w-4 text-amber-300"/> Inbox</div><div className="mt-1 text-[10px] text-white/45">{c.unread_notifications||0} unread</div></Link></div></div></section>
 <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{modules.map(({slug,name,text,icon:Icon,table})=><Link href={`/network/${slug}`} key={slug} className="group rounded-2xl border border-white/10 bg-white/[0.035] p-5 transition hover:-translate-y-1 hover:border-amber-300/25 hover:bg-white/[0.06]"><div className="flex items-start justify-between"><Icon className="h-7 w-7 text-amber-300"/><span className="rounded-full border border-white/10 px-2 py-1 text-[10px] text-white/45">{c[table]||0}</span></div><h2 className="mt-5 text-lg font-semibold">{name}</h2><p className="mt-2 text-sm leading-6 text-white/50">{text}</p></Link>)}</section>
 <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Quick href="/network/directory" icon={Users} title="Members & Family" text="Directory, profile privacy and five-digit identities."/><Quick href="/network/spaces" icon={NetworkIcon} title="Chapters & Circles" text="Join chapters, circles, committees and interest Spaces."/><Quick href="/network/growth" icon={GraduationCap} title="Mentorship & Scholarships" text="Mentor matching, guidance requests and scholarships."/><Quick href="/network/transactions" icon={ReceiptText} title="Transactions" text="Track external payments and receiver confirmation."/><Quick href="/network/governance" icon={Landmark} title="Governance" text="Positions, election/selection modes, nominations and voting."/><Quick href="/network/search" icon={Search} title="Universal Search" text="Permission-aware search across the entire Network."/><Quick href="/network/family-controls" icon={Baby} title="Family Controls" text="Guardian verification and policy-versioned consent for minors."/><Quick href="/network/safety" icon={Shield} title="Safety Center" text="Report concerns, block users and review moderation status."/><Quick href="/network/me" icon={UserRound} title="Me" text="Your identity, roles, family access, privacy and account shortcuts."/></section>
 {canAdmin&&<section className="mt-7"><Link href="/admin" className="block rounded-2xl border border-amber-300/20 bg-amber-300/[0.04] p-6"><div className="flex items-center justify-between gap-4"><div><div className="font-semibold">Admin Review Queue</div><p className="mt-2 text-sm text-white/50">Members, events, fundraising, businesses, family, governance, ForeverPoints, trust reports and scholarships.</p></div><Shield className="h-8 w-8 text-amber-300"/></div></Link></section>}
 </div><nav className="fixed inset-x-0 bottom-0 z-50 border-t border-white/10 bg-[#06150d]/95 px-2 py-2 backdrop-blur-xl md:hidden"><div className="mx-auto grid max-w-md grid-cols-5"><Mobile href="/network" icon={Shield} label="Home"/><Mobile href="/network/directory" icon={Users} label="Network"/><Mobile href="/network/community" icon={Plus} label="Create"/><Mobile href="/network/inbox" icon={Mail} label="Inbox"/><Mobile href="/network/me" icon={UserRound} label="Me"/></div></nav></main>}
function Quick({href,icon:Icon,title,text}:{href:string;icon:any;title:string;text:string}){return <Link href={href} className="rounded-2xl border border-white/10 bg-black/20 p-5"><Icon className="h-6 w-6 text-amber-300"/><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-white/50">{text}</p></Link>}
function Mobile({href,icon:Icon,label}:{href:string;icon:any;label:string}){return <Link href={href} className="flex flex-col items-center gap-1 py-1 text-[10px] text-white/65"><Icon className="h-5 w-5"/><span>{label}</span></Link>}
function Pending({user}:{user:SessionUser}){return <main className="min-h-screen bg-[#06150d] px-4 py-10 text-white sm:px-6"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3"><Shield className="h-9 w-9 text-amber-300"/><div><div className="font-bold">Together Forever Network</div><div className="text-xs text-white/50">Brotherhood • Est. 1977</div></div></Link><SignOutButton/></header><section className="mt-20 rounded-[2rem] border border-amber-300/20 bg-amber-300/[0.06] p-7 sm:p-10"><LockKeyhole className="h-11 w-11 text-amber-300"/><h1 className="mt-6 text-3xl font-semibold">Account authenticated. Membership link pending.</h1><p className="mt-4 max-w-2xl leading-7 text-white/65">Your secure identity exists, but Network access starts only after an authorized administrator links it to an approved Together Forever member or family record.</p><div className="mt-7 rounded-2xl border border-white/10 bg-black/20 p-5 text-sm text-white/70">Signed in as <strong className="text-white">{user.name||user.email||user.id}</strong>.</div></section></div></main>}
