import {NextResponse} from 'next/server';
import {auth} from '../../../../../lib/auth/server';
import {accessForAuthUser,hasPermission} from '../../../../../lib/access';
import {db} from '../../../../../lib/db';
import {deliverNotification,providerReadiness} from '../../../../../lib/notification-providers';
import {requireStepUp} from '../../../../../lib/security/step-up';
type U={id:string};type S={user?:U|null;data?:{user?:U|null}|null};
type Delivery={id:string;person_id:string;channel:'email'|'sms'|'whatsapp'|'push';attempt_count:number;email:string|null;phone:string|null;title:string;body:string};
async function gate(){const raw=(await auth.getSession()) as unknown as S;const u=raw.user??raw.data?.user??null;if(!u?.id)return {e:NextResponse.json({error:'Unauthorized'},{status:401})};const a=await accessForAuthUser(u.id);if(!a||a.accountStatus!=='active'||!hasPermission(a,'notifications.deliver'))return {e:NextResponse.json({error:'Forbidden'},{status:403})};return {a};}
export async function GET(){const g=await gate();if(g.e)return g.e;const s=db();const counts=await s`select channel,status,count(*)::int count from app.notification_deliveries group by channel,status order by channel,status`;return NextResponse.json({providers:providerReadiness(),counts});}
export async function POST(request:Request){const g=await gate();if(g.e)return g.e;const step=await requireStepUp(g.a!.personId,'communications.dispatch');if(step)return NextResponse.json(step,{status:428});const body=await request.json().catch(()=>({})) as Record<string,unknown>;const limit=Math.min(100,Math.max(1,Number(body.limit||50)));const announcementId=body.announcementId?String(body.announcementId):null;const s=db();
await s`update app.notification_deliveries nd set status='cancelled',last_error='Recipient opted out of this external critical-alert channel',updated_at=now() from app.notification_preferences np where np.person_id=nd.person_id and np.category='critical' and np.channel=nd.channel and np.enabled=false and nd.channel<>'in_app' and nd.status in ('queued','failed') and (${announcementId}::uuid is null or nd.announcement_id=${announcementId}::uuid)`;
const rows=await s`select nd.id::text,nd.person_id::text,nd.channel,nd.attempt_count,p.email,p.phone,a.title,a.body from app.notification_deliveries nd join app.persons p on p.id=nd.person_id join app.emergency_announcements a on a.id=nd.announcement_id where nd.channel in ('email','sms','whatsapp','push') and (nd.status='queued' or (nd.status='failed' and (nd.next_attempt_at is null or nd.next_attempt_at<=now()))) and (${announcementId}::uuid is null or nd.announcement_id=${announcementId}::uuid) order by nd.created_at asc limit ${limit}` as unknown as Delivery[];let sent=0,failed=0,deferred=0;const details:Array<{id:string;channel:string;status:string;error?:string}>=[];const ready=providerReadiness();for(const row of rows){const configured=ready[row.channel];if(!configured){await s`update app.notification_deliveries set attempt_count=attempt_count+1,last_error=${`Provider for ${row.channel} is not configured`},next_attempt_at=now()+interval '1 hour',updated_at=now() where id=${row.id}::uuid`;deferred++;details.push({id:row.id,channel:row.channel,status:'deferred',error:`Provider for ${row.channel} is not configured`});continue;}await s`update app.notification_deliveries set status='processing',attempt_count=attempt_count+1,updated_at=now() where id=${row.id}::uuid`;const result=await deliverNotification({channel:row.channel,title:row.title,body:row.body,email:row.email,phone:row.phone,personId:row.person_id});if(result.ok){await s`update app.notification_deliveries set status='sent',provider_message_id=${result.messageId||null},last_error=null,next_attempt_at=null,sent_at=now(),updated_at=now() where id=${row.id}::uuid`;sent++;details.push({id:row.id,channel:row.channel,status:'sent'});}else{const attempt=row.attempt_count+1;const minutes=Math.min(360,Math.max(5,Math.pow(2,Math.min(attempt,6))*5));await s`update app.notification_deliveries set status='failed',last_error=${result.error||'Provider rejected delivery'},next_attempt_at=now()+(${minutes}||' minutes')::interval,updated_at=now() where id=${row.id}::uuid`;failed++;details.push({id:row.id,channel:row.channel,status:'failed',error:result.error});}}
await s`insert into app.audit_logs(actor_person_id,action,object_type,after_data,reason) values(${g.a!.personId}::uuid,'communications.dispatch','notification_delivery',${JSON.stringify({announcementId,processed:rows.length,sent,failed,deferred})}::jsonb,'Provider-backed critical communications dispatch honoring recipient channel preferences')`;
return NextResponse.json({ok:true,processed:rows.length,sent,failed,deferred,providers:ready,details});}
