import {NextResponse} from 'next/server';
import {auth} from '../../../../lib/auth/server';
import {accessForAuthUser,hasPermission} from '../../../../lib/access';
import {db} from '../../../../lib/db';
import {requireStepUp} from '../../../../lib/security/step-up';

type U={id:string};type S={user?:U|null;data?:{user?:U|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as S;const u=raw.user??raw.data?.user??null;if(!u?.id)return {e:NextResponse.json({error:'Unauthorized'},{status:401})};const a=await accessForAuthUser(u.id);if(!a||a.accountStatus!=='active'||!(hasPermission(a,'imports.run')||hasPermission(a,'exports.run')||hasPermission(a,'imports.approve')))return {e:NextResponse.json({error:'Forbidden'},{status:403})};return {a};}

function validate(entity:string,row:Record<string,unknown>){const errors:string[]=[];if(entity==='benefits'){if(!String(row.title||'').trim())errors.push('title is required');if(row.foreverpointsCost!=null&&Number(row.foreverpointsCost)<0)errors.push('foreverpointsCost must be >= 0');}else if(entity==='events'){if(!String(row.title||'').trim())errors.push('title is required');if(!String(row.eventType||'').trim())errors.push('eventType is required');}else errors.push(`Unsupported import entity: ${entity}`);return errors;}

export async function GET(req:Request){const g=await gate();if(g.e)return g.e;const s=db();const u=new URL(req.url),jobId=u.searchParams.get('jobId');if(jobId){const jobs=await s`select id::text,job_type,entity_type,status,source_filename,source_url,mapping,validation_summary,result_url,requested_by_person_id::text,approved_by_person_id::text,created_at,updated_at,completed_at from app.data_transfer_jobs where id=${jobId}::uuid limit 1`;const rows=await s`select id::text,row_number,raw_data,mapped_data,validation_status from app.data_transfer_rows where job_id=${jobId}::uuid order by row_number limit 1000`;const errors=await s`select id::text,row_number,field_name,error_code,message,raw_value,created_at from app.data_transfer_errors where job_id=${jobId}::uuid order by row_number,id limit 1000`;const approvals=await s`select a.id::text,a.decision,a.notes,a.decided_at,p.full_name decided_by from app.data_transfer_approvals a join app.persons p on p.id=a.decided_by_person_id where a.job_id=${jobId}::uuid order by a.decided_at desc`;return NextResponse.json({job:(jobs as unknown as unknown[])[0]||null,rows,errors,approvals});}
const jobs=await s`select j.id::text,j.job_type,j.entity_type,j.status,j.source_filename,j.validation_summary,j.created_at,j.updated_at,count(r.id)::int row_count,count(r.id) filter(where r.validation_status='valid')::int valid_count,count(r.id) filter(where r.validation_status='error')::int error_count from app.data_transfer_jobs j left join app.data_transfer_rows r on r.job_id=j.id group by j.id order by j.created_at desc limit 100`;return NextResponse.json({jobs,supportedImports:['benefits','events'],permissions:{canRun:hasPermission(g.a!,'imports.run'),canApprove:hasPermission(g.a!,'imports.approve'),canExport:hasPermission(g.a!,'exports.run')}});}

export async function POST(req:Request){const g=await gate();if(g.e)return g.e;const b=await req.json() as Record<string,unknown>;const action=String(b.action||'');const s=db();try{
if(action==='create'){if(!hasPermission(g.a!,'imports.run'))return NextResponse.json({error:'Forbidden'},{status:403});const entity=String(b.entityType||'').trim();if(!['benefits','events'].includes(entity))return NextResponse.json({error:'Unsupported import entity'},{status:400});const rows=await s`insert into app.data_transfer_jobs(job_type,entity_type,status,source_filename,mapping,validation_summary,requested_by_person_id) values('import',${entity},'draft',${String(b.sourceFilename||'').trim()||null},${JSON.stringify(b.mapping||{})}::jsonb,'{}'::jsonb,${g.a!.personId}::uuid) returning id::text` as unknown as Array<{id:string}>;return NextResponse.json({ok:true,id:rows[0]?.id},{status:201});}
if(action==='stage'){if(!hasPermission(g.a!,'imports.run'))return NextResponse.json({error:'Forbidden'},{status:403});const jobId=String(b.jobId||''),input=Array.isArray(b.rows)?b.rows as Record<string,unknown>[]:[];if(!jobId||!input.length)return NextResponse.json({error:'jobId and rows required'},{status:400});if(input.length>1000)return NextResponse.json({error:'A single preview batch is limited to 1000 rows'},{status:400});const jobs=await s`select entity_type,status from app.data_transfer_jobs where id=${jobId}::uuid and job_type='import' limit 1` as unknown as Array<{entity_type:string;status:string}>;if(!jobs[0])return NextResponse.json({error:'Import job not found'},{status:404});if(!['draft','uploaded','mapping','validated'].includes(jobs[0].status))return NextResponse.json({error:'Job cannot be restaged in its current status'},{status:409});await s`delete from app.data_transfer_errors where job_id=${jobId}::uuid`;await s`delete from app.data_transfer_rows where job_id=${jobId}::uuid`;let valid=0,error=0;for(let i=0;i<input.length;i++){const row=input[i],errs=validate(jobs[0].entity_type,row),status=errs.length?'error':'valid';if(errs.length)error++;else valid++;await s`insert into app.data_transfer_rows(job_id,row_number,raw_data,mapped_data,validation_status) values(${jobId}::uuid,${i+1},${JSON.stringify(row)}::jsonb,${JSON.stringify(row)}::jsonb,${status})`;for(const msg of errs)await s`insert into app.data_transfer_errors(job_id,row_number,error_code,message) values(${jobId}::uuid,${i+1},'VALIDATION',${msg})`;}
const summary={rowCount:input.length,validCount:valid,errorCount:error,validatedAt:new Date().toISOString()};await s`update app.data_transfer_jobs set status=${error?'mapping':'validated'},validation_summary=${JSON.stringify(summary)}::jsonb,updated_at=now() where id=${jobId}::uuid`;return NextResponse.json({ok:true,...summary});}
if(action==='approve'){if(!hasPermission(g.a!,'imports.approve'))return NextResponse.json({error:'Forbidden'},{status:403});const step=await requireStepUp(g.a!.personId,'imports.approve');if(step)return NextResponse.json(step,{status:428});const jobId=String(b.jobId||''),decision=String(b.decision||'approved');if(!['approved','rejected'].includes(decision))return NextResponse.json({error:'Invalid decision'},{status:400});const jobs=await s`select status,requested_by_person_id::text from app.data_transfer_jobs where id=${jobId}::uuid limit 1` as unknown as Array<{status:string;requested_by_person_id:string}>;if(!jobs[0]||jobs[0].status!=='validated')return NextResponse.json({error:'Only validated jobs can be approved'},{status:409});if(jobs[0].requested_by_person_id===g.a!.personId)return NextResponse.json({error:'The requester cannot approve their own import'},{status:403});await s`insert into app.data_transfer_approvals(job_id,decision,notes,decided_by_person_id) values(${jobId}::uuid,${decision},${String(b.notes||'').trim()||null},${g.a!.personId}::uuid)`;await s`update app.data_transfer_jobs set status=${decision==='approved'?'ready':'cancelled'},approved_by_person_id=case when ${decision}='approved' then ${g.a!.personId}::uuid else approved_by_person_id end,updated_at=now() where id=${jobId}::uuid`;return NextResponse.json({ok:true,status:decision==='approved'?'ready':'cancelled'});}
if(action==='execute'){if(!hasPermission(g.a!,'imports.run'))return NextResponse.json({error:'Forbidden'},{status:403});const step=await requireStepUp(g.a!.personId,'imports.execute');if(step)return NextResponse.json(step,{status:428});const jobId=String(b.jobId||'');const jobs=await s`select entity_type,status,requested_by_person_id::text,approved_by_person_id::text from app.data_transfer_jobs where id=${jobId}::uuid limit 1` as unknown as Array<{entity_type:string;status:string;requested_by_person_id:string;approved_by_person_id:string|null}>;if(!jobs[0]||jobs[0].status!=='ready'||!jobs[0].approved_by_person_id)return NextResponse.json({error:'Import must be validated and separately approved before execution'},{status:409});const invalid=await s`select count(*)::int n from app.data_transfer_rows where job_id=${jobId}::uuid and validation_status<>'valid'` as unknown as Array<{n:number}>;if((invalid[0]?.n||0)>0)return NextResponse.json({error:'Import still contains invalid rows'},{status:409});await s`update app.data_transfer_jobs set status='running',updated_at=now() where id=${jobId}::uuid`;
let processed=0;if(jobs[0].entity_type==='benefits'){const result=await s`insert into app.member_benefits(title,provider_name,category,description,terms,external_url,foreverpoints_cost,status,created_by_person_id) select trim(mapped_data->>'title'),nullif(trim(mapped_data->>'providerName'),''),coalesce(nullif(trim(mapped_data->>'category'),''),'general'),nullif(trim(mapped_data->>'description'),''),nullif(trim(mapped_data->>'terms'),''),nullif(trim(mapped_data->>'externalUrl'),''),case when mapped_data ? 'foreverpointsCost' and mapped_data->>'foreverpointsCost'<>'' then (mapped_data->>'foreverpointsCost')::bigint else null end,case when mapped_data->>'status' in ('draft','active','paused','expired','archived') then mapped_data->>'status' else 'draft' end,${g.a!.personId}::uuid from app.data_transfer_rows where job_id=${jobId}::uuid and validation_status='valid' returning id`;processed=(result as unknown as unknown[]).length;}else if(jobs[0].entity_type==='events'){const result=await s`insert into app.events(title,event_type,description,timezone,location_name,location_address,meeting_url,status,owner_person_id) select trim(mapped_data->>'title'),trim(mapped_data->>'eventType'),nullif(trim(mapped_data->>'description'),''),coalesce(nullif(trim(mapped_data->>'timezone'),''),'UTC'),nullif(trim(mapped_data->>'locationName'),''),nullif(trim(mapped_data->>'locationAddress'),''),nullif(trim(mapped_data->>'meetingUrl'),''),'draft',${g.a!.personId}::uuid from app.data_transfer_rows where job_id=${jobId}::uuid and validation_status='valid' returning id`;processed=(result as unknown as unknown[]).length;}else return NextResponse.json({error:'No executor registered for this entity'},{status:400});
await s`update app.data_transfer_jobs set status='completed',validation_summary=coalesce(validation_summary,'{}'::jsonb)||${JSON.stringify({executedAt:new Date().toISOString(),processedCount:processed})}::jsonb,completed_at=now(),updated_at=now() where id=${jobId}::uuid`;return NextResponse.json({ok:true,processed});}
return NextResponse.json({error:'Unknown action'},{status:400});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Transfer action failed'},{status:400});}}
