import { NextResponse } from 'next/server';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser,hasPermission,hasScopedPermission } from '../../../../lib/access';
import { db } from '../../../../lib/db';
import { requireStepUp } from '../../../../lib/security/step-up';
type SessionUser={id:string};type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
async function gate(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')return {error:NextResponse.json({error:'Forbidden'},{status:403})};return {access};}
export async function GET(request:Request){const g=await gate();if(g.error)return g.error;const s=db();const spaceId=new URL(request.url).searchParams.get('spaceId');const rows=await s`select sp.id::text,sp.space_type,sp.name,sp.slug,sp.description,sp.is_active,sp.created_by_person_id::text,coalesce(ap.policy_type,'network') audience_type,coalesce(sm.membership_status,'none') membership_status,coalesce((select count(*)::int from app.space_members x where x.space_id=sp.id and x.membership_status='active'),0) member_count,coalesce((select count(*)::int from app.posts p where p.space_id=sp.id and p.status='published'),0) post_count from app.spaces sp left join app.space_members sm on sm.space_id=sp.id and sm.person_id=${g.access!.personId}::uuid left join app.audience_policies ap on ap.id=sp.audience_policy_id where sp.is_active=true and (ap.id is null or ap.policy_type in ('public','network','family') or (ap.policy_type='m_only' and ${g.access!.relationshipPrefix}='M') or sp.created_by_person_id=${g.access!.personId}::uuid or sm.membership_status in ('active','invited','pending')) order by case when sm.membership_status='active' then 0 else 1 end,sp.space_type,sp.name`;
let posts:unknown[]=[];let selected:Record<string,unknown>|null=null;if(spaceId){selected=(rows as unknown as Array<Record<string,unknown>>).find(r=>r.id===spaceId)||null;if(!selected)return NextResponse.json({error:'Space not found or not visible'},{status:404});const canModerate=hasPermission(g.access!,'community.moderate')||hasScopedPermission(g.access!,'community.moderate','space',spaceId);posts=await s`select p.id::text,p.post_type,p.title,p.body,p.status,p.created_at,p.author_person_id::text,coalesce(person.display_name,person.full_name) author_name,mc.code author_code from app.posts p join app.persons person on person.id=p.author_person_id left join app.membership_codes mc on mc.person_id=person.id where p.space_id=${spaceId}::uuid and (p.status='published' or p.author_person_id=${g.access!.personId}::uuid or ${canModerate}) order by p.created_at desc limit 100`;}
return NextResponse.json({rows,selected,posts,canCreate:hasPermission(g.access!,'spaces.create'),canManage:hasPermission(g.access!,'spaces.manage'),canPost:hasPermission(g.access!,'community.post'),canModerateSelected:spaceId?hasPermission(g.access!,'community.moderate')||hasScopedPermission(g.access!,'community.moderate','space',spaceId):false});}
export async function POST(request:Request){const g=await gate();if(g.error)return g.error;const b=await request.json() as {action?:string;spaceId?:string;name?:string;spaceType?:string;description?:string;audience?:string;title?:string;body?:string;postType?:string;postId?:string;status?:string};const s=db();try{if(b.action==='create'){if(!hasPermission(g.access!,'spaces.create'))return NextResponse.json({error:'Forbidden'},{status:403});const name=b.name?.trim()||'';if(!name)return NextResponse.json({error:'Name required'},{status:400});const type=b.spaceType||'circle';if(!['network','chapter','circle','committee','board','family','interest','custom'].includes(type))return NextResponse.json({error:'Invalid space type'},{status:400});const policyType=b.audience||'network';const p=await s`select id::text from app.audience_policies where policy_type=${policyType} and is_active=true limit 1` as unknown as Array<{id:string}>;const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36);const row=await s`insert into app.spaces(space_type,name,slug,description,audience_policy_id,created_by_person_id,is_active) values (${type},${name},${slug},${b.description?.trim()||null},${p[0]?.id||null}::uuid,${g.access!.personId}::uuid,true) returning id::text` as unknown as Array<{id:string}>;await s`insert into app.space_members(space_id,person_id,membership_status,joined_at) values (${row[0].id}::uuid,${g.access!.personId}::uuid,'active',now()) on conflict(space_id,person_id) do update set membership_status='active',joined_at=now()`;return NextResponse.json({ok:true,id:row[0].id},{status:201});}
if(!b.spaceId)return NextResponse.json({error:'spaceId required'},{status:400});const visible=await s`select sp.id::text from app.spaces sp left join app.audience_policies ap on ap.id=sp.audience_policy_id left join app.space_members sm on sm.space_id=sp.id and sm.person_id=${g.access!.personId}::uuid where sp.id=${b.spaceId}::uuid and sp.is_active=true and (ap.id is null or ap.policy_type in ('public','network','family') or (ap.policy_type='m_only' and ${g.access!.relationshipPrefix}='M') or sp.created_by_person_id=${g.access!.personId}::uuid or sm.membership_status in ('active','invited','pending')) limit 1`;if(!(visible as unknown as unknown[])[0])return NextResponse.json({error:'Space not found or not visible'},{status:404});
if(b.action==='join'){await s`insert into app.space_members(space_id,person_id,membership_status,joined_at) values (${b.spaceId}::uuid,${g.access!.personId}::uuid,'active',now()) on conflict(space_id,person_id) do update set membership_status='active',joined_at=now()`;return NextResponse.json({ok:true});}
if(b.action==='leave'){await s`update app.space_members set membership_status='removed' where space_id=${b.spaceId}::uuid and person_id=${g.access!.personId}::uuid`;return NextResponse.json({ok:true});}
if(b.action==='post.create'){if(!hasPermission(g.access!,'community.post'))return NextResponse.json({error:'Forbidden'},{status:403});const member=await s`select 1 from app.space_members where space_id=${b.spaceId}::uuid and person_id=${g.access!.personId}::uuid and membership_status='active' limit 1`;if(!(member as unknown as unknown[])[0])return NextResponse.json({error:'Join this space before posting'},{status:403});const title=b.title?.trim()||'',body=b.body?.trim()||'',postType=b.postType||'update';if(!title||!body)return NextResponse.json({error:'Title and body required'},{status:400});if(!['update','need','offer','announcement','question','milestone','family_announcement','other'].includes(postType))return NextResponse.json({error:'Invalid post type'},{status:400});const created=await s`insert into app.posts(post_type,title,body,audience_policy_id,space_id,author_person_id,status) select ${postType},${title},${body},sp.audience_policy_id,sp.id,${g.access!.personId}::uuid,'published' from app.spaces sp where sp.id=${b.spaceId}::uuid returning id::text` as unknown as Array<{id:string}>;return NextResponse.json({ok:true,id:created[0]?.id},{status:201});}
if(b.action==='post.moderate'){const can=hasPermission(g.access!,'community.moderate')||hasScopedPermission(g.access!,'community.moderate','space',b.spaceId);if(!can)return NextResponse.json({error:'Forbidden'},{status:403});const step=await requireStepUp(g.access!.personId,'community.moderate');if(step)return NextResponse.json(step,{status:428});const status=b.status||'hidden';if(!b.postId||!['published','hidden','archived'].includes(status))return NextResponse.json({error:'Invalid moderation action'},{status:400});await s`update app.posts set status=${status},updated_at=now() where id=${b.postId}::uuid and space_id=${b.spaceId}::uuid`;await s`insert into app.audit_logs(actor_person_id,action,object_type,object_id,after_data) values (${g.access!.personId}::uuid,'space.post.moderate','post',${b.postId}::uuid,${JSON.stringify({spaceId:b.spaceId,status})}::jsonb)`;return NextResponse.json({ok:true});}
return NextResponse.json({error:'Unknown action'},{status:400});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Space action failed'},{status:400});}}
