import { NextResponse } from 'next/server';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser, hasPermission } from '../../../../lib/access';
import { db } from '../../../../lib/db';

type SessionUser={id:string};
type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
type Access=NonNullable<Awaited<ReturnType<typeof accessForAuthUser>>>;

type ModuleConfig={table:string;createPermission:string;moderatePermission?:string;ownerColumn:string;titleColumn:string;statusColumn:string;insert:(body:Record<string,unknown>,access:Access,audienceId:string)=>Promise<unknown[]>};

async function gate(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')return {error:NextResponse.json({error:'Forbidden'},{status:403})};return {access};}

function configs():Record<string,ModuleConfig>{
  return {
    events:{table:'events',createPermission:'events.create',moderatePermission:'events.approve',ownerColumn:'suggested_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(body,a,audienceId)=>{const sql=db();return await sql`insert into app.events(title,event_type,description,starts_at,ends_at,timezone,location_name,meeting_url,audience_policy_id,status,suggested_by_person_id,owner_person_id) values (${String(body.title||'').trim()},${String(body.eventType||'get_together')},${String(body.description||'').trim()||null},${body.startsAt?String(body.startsAt):null}::timestamptz,${body.endsAt?String(body.endsAt):null}::timestamptz,${String(body.timezone||'UTC')},${String(body.location||'').trim()||null},${String(body.externalUrl||'').trim()||null},${audienceId}::uuid,'suggested',${a.personId}::uuid,${a.personId}::uuid) returning id::text,title,status,created_at` as unknown as unknown[];}},
    opportunities:{table:'opportunities',createPermission:'opportunities.create',moderatePermission:'opportunities.moderate',ownerColumn:'posted_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(body,a,audienceId)=>{const sql=db();return await sql`insert into app.opportunities(opportunity_type,title,organization_name,description,location_text,work_mode,compensation_text,application_url,deadline,audience_policy_id,posted_by_person_id,status) values (${String(body.type||'job')},${String(body.title||'').trim()},${String(body.organization||'').trim()||null},${String(body.description||'').trim()||null},${String(body.location||'').trim()||null},${String(body.workMode||'').trim()||null},${String(body.compensation||'').trim()||null},${String(body.externalUrl||'').trim()||null},${body.deadline?String(body.deadline):null}::timestamptz,${audienceId}::uuid,${a.personId}::uuid,'published') returning id::text,title,status,created_at` as unknown as unknown[];}},
    marketplace:{table:'listings',createPermission:'marketplace.create',moderatePermission:'marketplace.moderate',ownerColumn:'seller_person_id',titleColumn:'title',statusColumn:'status',insert:async(body,a,audienceId)=>{const sql=db();return await sql`insert into app.listings(listing_type,title,description,asking_price,currency,location_text,attributes,audience_policy_id,seller_person_id,status) values (${String(body.type||'general')},${String(body.title||'').trim()},${String(body.description||'').trim()||null},${body.amount?Number(body.amount):null},${String(body.currency||'PKR')},${String(body.location||'').trim()||null},${JSON.stringify(body.attributes||{})}::jsonb,${audienceId}::uuid,${a.personId}::uuid,'published') returning id::text,title,status,created_at` as unknown as unknown[];}},
    fundraising:{table:'campaigns',createPermission:'fundraising.propose',moderatePermission:'fundraising.manage',ownerColumn:'suggested_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(body,a,audienceId)=>{const sql=db();return await sql`insert into app.campaigns(campaign_type,title,description,goal_amount,currency,starts_at,ends_at,audience_policy_id,suggested_by_person_id,owner_person_id,status) values (${String(body.type||'cause')},${String(body.title||'').trim()},${String(body.description||'').trim()||null},${body.amount?Number(body.amount):null},${String(body.currency||'PKR')},now(),${body.deadline?String(body.deadline):null}::timestamptz,${audienceId}::uuid,${a.personId}::uuid,${a.personId}::uuid,'suggested') returning id::text,title,status,created_at` as unknown as unknown[];}},
    gallery:{table:'media_albums',createPermission:'media.create',moderatePermission:'media.moderate',ownerColumn:'created_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(body,a,audienceId)=>{const sql=db();return await sql`insert into app.media_albums(title,description,album_type,source_provider,external_url,audience_policy_id,created_by_person_id,status) values (${String(body.title||'').trim()},${String(body.description||'').trim()||null},${String(body.type||'gallery')},${String(body.provider||'external')},${String(body.externalUrl||'').trim()||null},${audienceId}::uuid,${a.personId}::uuid,'published') returning id::text,title,status,created_at` as unknown as unknown[];}},
    businesses:{table:'businesses',createPermission:'business.create',moderatePermission:'business.moderate',ownerColumn:'created_by_person_id',titleColumn:'name',statusColumn:'verification_status',insert:async(body,a,audienceId)=>{const sql=db();const name=String(body.title||'').trim();const slug=(name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36));return await sql`insert into app.businesses(name,slug,description,industry,website_url,location_text,audience_policy_id,verification_status,created_by_person_id) values (${name},${slug},${String(body.description||'').trim()||null},${String(body.type||'general')},${String(body.externalUrl||'').trim()||null},${String(body.location||'').trim()||null},${audienceId}::uuid,'pending',${a.personId}::uuid) returning id::text,name as title,verification_status as status,created_at` as unknown as unknown[];}},
    community:{table:'posts',createPermission:'community.post',moderatePermission:'community.moderate',ownerColumn:'author_person_id',titleColumn:'title',statusColumn:'status',insert:async(body,a,audienceId)=>{const sql=db();return await sql`insert into app.posts(post_type,title,body,audience_policy_id,author_person_id,status) values (${String(body.type||'update')},${String(body.title||'').trim()},${String(body.description||'').trim()||null},${audienceId}::uuid,${a.personId}::uuid,'published') returning id::text,title,status,created_at` as unknown as unknown[];}},
    proposals:{table:'proposals',createPermission:'governance.propose',moderatePermission:'governance.configure',ownerColumn:'proposed_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(body,a,audienceId)=>{const sql=db();return await sql`insert into app.proposals(title,body,proposed_by_person_id,audience_policy_id,voting_policy,status) values (${String(body.title||'').trim()},${String(body.description||'').trim()||null},${a.personId}::uuid,${audienceId}::uuid,'{}'::jsonb,'submitted') returning id::text,title,status,created_at` as unknown as unknown[];}},
  };
}

async function audienceId(policyType:string){const sql=db();const rows=await sql`select id::text from app.audience_policies where is_active=true and policy_type=${policyType} order by is_system desc limit 1` as unknown as Array<{id:string}>;return rows[0]?.id||(await sql`select id::text from app.audience_policies where is_active=true and policy_type='network' limit 1` as unknown as Array<{id:string}>)[0]?.id;}

export async function GET(_request:Request,{params}:{params:Promise<{module:string}>}){const g=await gate();if(g.error)return g.error;const {module}=await params;const c=configs()[module];if(!c)return NextResponse.json({error:'Unknown module'},{status:404});const sql=db();const rows=await sql.query(`select id::text, ${c.titleColumn} as title, ${c.statusColumn} as status, created_at from app.${c.table} order by created_at desc limit 100`) as unknown as unknown[];return NextResponse.json({module,rows,canCreate:hasPermission(g.access!,c.createPermission),canModerate:c.moderatePermission?hasPermission(g.access!,c.moderatePermission):false});}

export async function POST(request:Request,{params}:{params:Promise<{module:string}>}){const g=await gate();if(g.error)return g.error;const {module}=await params;const c=configs()[module];if(!c)return NextResponse.json({error:'Unknown module'},{status:404});if(!hasPermission(g.access!,c.createPermission))return NextResponse.json({error:'Forbidden'},{status:403});const body=await request.json() as Record<string,unknown>;if(!String(body.title||'').trim())return NextResponse.json({error:'Title is required'},{status:400});const audience=await audienceId(String(body.audience||'network'));if(!audience)return NextResponse.json({error:'Audience policy unavailable'},{status:500});try{const created=await c.insert(body,g.access!,audience);return NextResponse.json({created},{status:201});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to create record'},{status:400});}}

export async function PATCH(request:Request,{params}:{params:Promise<{module:string}>}){const g=await gate();if(g.error)return g.error;const {module}=await params;const c=configs()[module];if(!c)return NextResponse.json({error:'Unknown module'},{status:404});const body=await request.json() as {id?:string;title?:string;status?:string};if(!body.id)return NextResponse.json({error:'id required'},{status:400});const sql=db();const owner=await sql.query(`select ${c.ownerColumn}::text as owner from app.${c.table} where id=$1::uuid limit 1`,[body.id]) as unknown as Array<{owner:string|null}>;const isOwner=owner[0]?.owner===g.access!.personId;const canModerate=!!c.moderatePermission&&hasPermission(g.access!,c.moderatePermission);if(!isOwner&&!canModerate)return NextResponse.json({error:'Forbidden'},{status:403});if(body.title)await sql.query(`update app.${c.table} set ${c.titleColumn}=$1, updated_at=now() where id=$2::uuid`,[body.title.trim(),body.id]);if(body.status&&canModerate)await sql.query(`update app.${c.table} set ${c.statusColumn}=$1, updated_at=now() where id=$2::uuid`,[body.status,body.id]);return GET(request,{params:Promise.resolve({module})});}

export async function DELETE(request:Request,{params}:{params:Promise<{module:string}>}){const g=await gate();if(g.error)return g.error;const {module}=await params;const c=configs()[module];if(!c)return NextResponse.json({error:'Unknown module'},{status:404});const id=new URL(request.url).searchParams.get('id');if(!id)return NextResponse.json({error:'id required'},{status:400});const sql=db();const owner=await sql.query(`select ${c.ownerColumn}::text as owner from app.${c.table} where id=$1::uuid limit 1`,[id]) as unknown as Array<{owner:string|null}>;const isOwner=owner[0]?.owner===g.access!.personId;const canModerate=!!c.moderatePermission&&hasPermission(g.access!,c.moderatePermission);if(!isOwner&&!canModerate)return NextResponse.json({error:'Forbidden'},{status:403});await sql.query(`update app.${c.table} set ${c.statusColumn}='archived', updated_at=now() where id=$1::uuid`,[id]);return GET(request,{params:Promise.resolve({module})});}
