import { NextResponse } from 'next/server';
import { auth } from '../../../../lib/auth/server';
import { accessForAuthUser, hasPermission } from '../../../../lib/access';
import { db } from '../../../../lib/db';

type SessionUser={id:string};
type SessionResult={user?:SessionUser|null;data?:{user?:SessionUser|null}|null};
type Access=NonNullable<Awaited<ReturnType<typeof accessForAuthUser>>>;
type ModuleConfig={table:string;createPermission:string;moderatePermission?:string;ownerColumn:string;titleColumn:string;statusColumn:string;archiveStatus?:string;insert:(body:Record<string,unknown>,access:Access,audienceId:string)=>Promise<unknown[]>};

async function gate(){const raw=(await auth.getSession()) as unknown as SessionResult;const user=raw.user??raw.data?.user??null;if(!user?.id)return {error:NextResponse.json({error:'Unauthorized'},{status:401})};const access=await accessForAuthUser(user.id);if(!access||access.accountStatus!=='active')return {error:NextResponse.json({error:'Forbidden'},{status:403})};return {access};}

function configs():Record<string,ModuleConfig>{return {
 events:{table:'events',createPermission:'events.create',moderatePermission:'events.approve',ownerColumn:'suggested_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(b,a,x)=>{const s=db();return await s`insert into app.events(title,event_type,description,starts_at,ends_at,timezone,location_name,meeting_url,audience_policy_id,status,suggested_by_person_id,owner_person_id) values (${String(b.title||'').trim()},${String(b.eventType||'get_together')},${String(b.description||'').trim()||null},${b.startsAt?String(b.startsAt):null}::timestamptz,${b.endsAt?String(b.endsAt):null}::timestamptz,${String(b.timezone||'UTC')},${String(b.location||'').trim()||null},${String(b.externalUrl||'').trim()||null},${x}::uuid,'suggested',${a.personId}::uuid,${a.personId}::uuid) returning id::text,title,status,created_at` as unknown as unknown[];}},
 opportunities:{table:'opportunities',createPermission:'opportunities.create',moderatePermission:'opportunities.moderate',ownerColumn:'posted_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(b,a,x)=>{const s=db();return await s`insert into app.opportunities(opportunity_type,title,organization_name,description,location_text,work_mode,compensation_text,application_url,deadline,audience_policy_id,posted_by_person_id,status) values (${String(b.type||'job')},${String(b.title||'').trim()},${String(b.organization||'').trim()||null},${String(b.description||'').trim()||null},${String(b.location||'').trim()||null},${String(b.workMode||'').trim()||null},${String(b.compensation||'').trim()||null},${String(b.externalUrl||'').trim()||null},${b.deadline?String(b.deadline):null}::timestamptz,${x}::uuid,${a.personId}::uuid,'published') returning id::text,title,status,created_at` as unknown as unknown[];}},
 marketplace:{table:'listings',createPermission:'marketplace.create',moderatePermission:'marketplace.moderate',ownerColumn:'seller_person_id',titleColumn:'title',statusColumn:'status',insert:async(b,a,x)=>{const s=db();return await s`insert into app.listings(listing_type,title,description,asking_price,currency,location_text,attributes,audience_policy_id,seller_person_id,status) values (${String(b.type||'general')},${String(b.title||'').trim()},${String(b.description||'').trim()||null},${b.amount?Number(b.amount):null},${String(b.currency||'PKR')},${String(b.location||'').trim()||null},${JSON.stringify(b.attributes||{})}::jsonb,${x}::uuid,${a.personId}::uuid,'published') returning id::text,title,status,created_at` as unknown as unknown[];}},
 fundraising:{table:'campaigns',createPermission:'fundraising.propose',moderatePermission:'fundraising.manage',ownerColumn:'suggested_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(b,a,x)=>{const s=db();return await s`insert into app.campaigns(campaign_type,title,description,goal_amount,currency,starts_at,ends_at,audience_policy_id,suggested_by_person_id,owner_person_id,status) values (${String(b.type||'fundraiser')},${String(b.title||'').trim()},${String(b.description||'').trim()||null},${b.amount?Number(b.amount):null},${String(b.currency||'PKR')},now(),${b.deadline?String(b.deadline):null}::timestamptz,${x}::uuid,${a.personId}::uuid,${a.personId}::uuid,'suggested') returning id::text,title,status,created_at` as unknown as unknown[];}},
 gallery:{table:'media_albums',createPermission:'media.create',moderatePermission:'media.moderate',ownerColumn:'created_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(b,a,x)=>{const s=db();return await s`insert into app.media_albums(title,description,album_type,source_provider,external_url,audience_policy_id,created_by_person_id,status) values (${String(b.title||'').trim()},${String(b.description||'').trim()||null},${String(b.type||'gallery')},${String(b.provider||'external')},${String(b.externalUrl||'').trim()||null},${x}::uuid,${a.personId}::uuid,'published') returning id::text,title,status,created_at` as unknown as unknown[];}},
 businesses:{table:'businesses',createPermission:'business.create',moderatePermission:'business.moderate',ownerColumn:'created_by_person_id',titleColumn:'name',statusColumn:'verification_status',archiveStatus:'suspended',insert:async(b,a,x)=>{const s=db();const name=String(b.title||'').trim();const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString(36);return await s`insert into app.businesses(name,slug,description,industry,website_url,location_text,audience_policy_id,verification_status,created_by_person_id) values (${name},${slug},${String(b.description||'').trim()||null},${String(b.type||'general')},${String(b.externalUrl||'').trim()||null},${String(b.location||'').trim()||null},${x}::uuid,'unverified',${a.personId}::uuid) returning id::text,name as title,verification_status as status,created_at` as unknown as unknown[];}},
 community:{table:'posts',createPermission:'community.post',moderatePermission:'community.moderate',ownerColumn:'author_person_id',titleColumn:'title',statusColumn:'status',insert:async(b,a,x)=>{const s=db();return await s`insert into app.posts(post_type,title,body,audience_policy_id,author_person_id,status) values (${String(b.type||'update')},${String(b.title||'').trim()},${String(b.description||'').trim()||null},${x}::uuid,${a.personId}::uuid,'published') returning id::text,title,status,created_at` as unknown as unknown[];}},
 proposals:{table:'proposals',createPermission:'governance.propose',moderatePermission:'governance.configure',ownerColumn:'proposed_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(b,a,x)=>{const s=db();return await s`insert into app.proposals(title,body,proposed_by_person_id,audience_policy_id,voting_policy,status) values (${String(b.title||'').trim()},${String(b.description||'').trim()||null},${a.personId}::uuid,${x}::uuid,'{}'::jsonb,'submitted') returning id::text,title,status,created_at` as unknown as unknown[];}},
 'family-life':{table:'family_requests',createPermission:'family.manage_own',moderatePermission:'family.verify',ownerColumn:'created_by_person_id',titleColumn:'title',statusColumn:'status',insert:async(b,a,x)=>{const s=db();return await s`insert into app.family_requests(request_type,title,description,request_data,audience_policy_id,created_by_person_id,guardian_person_id,status) values (${String(b.type||'other')},${String(b.title||'').trim()},${String(b.description||'').trim()||null},${JSON.stringify({location:b.location||null,externalUrl:b.externalUrl||null})}::jsonb,${x}::uuid,${a.personId}::uuid,${a.relationshipPrefix==='M'?a.personId:null}::uuid,'pending') returning id::text,title,status,created_at` as unknown as unknown[];}},
};}

async function audienceId(policyType:string){const s=db();const r=await s`select id::text from app.audience_policies where is_active=true and policy_type=${policyType} order by is_system desc limit 1` as unknown as Array<{id:string}>;if(r[0]?.id)return r[0].id;const f=await s`select id::text from app.audience_policies where is_active=true and policy_type='network' limit 1` as unknown as Array<{id:string}>;return f[0]?.id;}

export async function GET(_r:Request,{params}:{params:Promise<{module:string}>}){const g=await gate();if(g.error)return g.error;const {module}=await params;const c=configs()[module];if(!c)return NextResponse.json({error:'Unknown module'},{status:404});const s=db();const rows=await s.query(`select t.id::text, t.${c.titleColumn} as title, t.${c.statusColumn} as status, t.created_at from app.${c.table} t left join app.audience_policies ap on ap.id=t.audience_policy_id where ap.id is null or ap.policy_type in ('public','network','family') or (ap.policy_type='m_only' and $1='M') or t.${c.ownerColumn}=$2::uuid order by t.created_at desc limit 100`,[g.access!.relationshipPrefix,g.access!.personId]) as unknown as unknown[];return NextResponse.json({module,rows,canCreate:hasPermission(g.access!,c.createPermission),canModerate:c.moderatePermission?hasPermission(g.access!,c.moderatePermission):false});}
export async function POST(r:Request,{params}:{params:Promise<{module:string}>}){const g=await gate();if(g.error)return g.error;const {module}=await params;const c=configs()[module];if(!c)return NextResponse.json({error:'Unknown module'},{status:404});if(!hasPermission(g.access!,c.createPermission))return NextResponse.json({error:'Forbidden'},{status:403});const b=await r.json() as Record<string,unknown>;if(!String(b.title||'').trim())return NextResponse.json({error:'Title is required'},{status:400});const x=await audienceId(String(b.audience||'network'));if(!x)return NextResponse.json({error:'Audience policy unavailable'},{status:500});try{return NextResponse.json({created:await c.insert(b,g.access!,x)},{status:201});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Unable to create record'},{status:400});}}
export async function PATCH(r:Request,{params}:{params:Promise<{module:string}>}){const g=await gate();if(g.error)return g.error;const {module}=await params;const c=configs()[module];if(!c)return NextResponse.json({error:'Unknown module'},{status:404});const b=await r.json() as {id?:string;title?:string;status?:string};if(!b.id)return NextResponse.json({error:'id required'},{status:400});const s=db();const owner=await s.query(`select ${c.ownerColumn}::text as owner from app.${c.table} where id=$1::uuid limit 1`,[b.id]) as unknown as Array<{owner:string|null}>;const own=owner[0]?.owner===g.access!.personId;const mod=!!c.moderatePermission&&hasPermission(g.access!,c.moderatePermission);if(!own&&!mod)return NextResponse.json({error:'Forbidden'},{status:403});if(b.title)await s.query(`update app.${c.table} set ${c.titleColumn}=$1, updated_at=now() where id=$2::uuid`,[b.title.trim(),b.id]);if(b.status&&mod)await s.query(`update app.${c.table} set ${c.statusColumn}=$1, updated_at=now() where id=$2::uuid`,[b.status,b.id]);return GET(r,{params:Promise.resolve({module})});}
export async function DELETE(r:Request,{params}:{params:Promise<{module:string}>}){const g=await gate();if(g.error)return g.error;const {module}=await params;const c=configs()[module];if(!c)return NextResponse.json({error:'Unknown module'},{status:404});const id=new URL(r.url).searchParams.get('id');if(!id)return NextResponse.json({error:'id required'},{status:400});const s=db();const owner=await s.query(`select ${c.ownerColumn}::text as owner from app.${c.table} where id=$1::uuid limit 1`,[id]) as unknown as Array<{owner:string|null}>;const own=owner[0]?.owner===g.access!.personId;const mod=!!c.moderatePermission&&hasPermission(g.access!,c.moderatePermission);if(!own&&!mod)return NextResponse.json({error:'Forbidden'},{status:403});await s.query(`update app.${c.table} set ${c.statusColumn}=$1, updated_at=now() where id=$2::uuid`,[c.archiveStatus||'archived',id]);return GET(r,{params:Promise.resolve({module})});}
